### ISSUE TITLE
Request: pushback

### ISSUE THREAD

**Issue by diazona** [erikrose/more-itertools#106]
I'd like to suggest adding a wrapper that allows pushing a value back on to an iterator, so that the next call to `next(it)` will return the pushed value before the next element from the underlying iterable. I find myself wanting this from time to time (usually in parsing applications), and I could have sworn it was implemented somewhere standard, but I looked around and couldn't find it. Would this be a good addition to more-itertools?

I do have code to offer, but I'm posing this as an issue instead of a pull request because I have a dilemma. I've come up with two implementations, one [as a generator function](https://github.com/diazona/more-itertools/tree/pushback_function)
```python
def pushback(iterable, maxlen=None):
    iterable = iter(iterable)
    # add 1 to account for the append(None)
    stack = deque(maxlen=maxlen + 1 if maxlen is not None else None)
    while True:
        if stack:
            e = stack.pop()
        else:
            e = next(iterable)
        sent = yield e
        if sent is not None:
            stack.append(sent)
            stack.append(None) # dummy value to return from send()
```
and the other [as a class](https://github.com/diazona/more-itertools/tree/pushback_class)
```python
class pushback:
    def __init__(self, iterable, maxlen=None):
        self.iterable = iter(iterable)
        self.stack = deque(maxlen=maxlen)
    def __iter__(self):
        return self
    def __next__(self):
        return self.stack.pop() if self.stack else next(self.iterable)
    def send(self, value):
        self.stack.append(value)
```
The function implementation is about twice as fast in my preliminary tests (using IPython)
```
In [13]: %timeit list(pushback_function(range(10)))
100000 loops, best of 3: 5.45 µs per loop
In [14]: %timeit list(pushback_class(range(10)))
100000 loops, best of 3: 10.8 µs per loop
```
On the other hand the class implementation is conceptually cleaner, and also does not need to be "primed" by calling `next(it)` before sending in a value with `it.send(x)`.

Now, in most cases, you can prime the generator iterator without losing an item by running `it.send(next(it))`, and that could be done in a wrapper function to make it transparent to client code. But only the class implementation allows pushing in front of an empty iterable (admittedly a rather pathological use case):
```python console
>>> it = pushback([])
>>> it.send(10)
>>> list(it)
[10]
```
So my point is: if this is something you want for more-itertools, which implementation to use? Or is there a way to "fix" one of them to make it strictly better than the other, that I'm not seeing? (Or does this whole thing already exist and I wasted an evening?)

**Comment by bbayles** [comment]
Hey, thanks for the writeup - this is interesting.

My first reaction is to wonder whether `itertools.chain` is the implementation you were thinking of?
Suppose I need to put some values ahead of my iterator:
```python
>>> from itertools import chain
... 
... it = (x for x in 'body')
... it = chain('header ', it)
... list(it)
['h', 'e', 'a', 'd', 'e', 'r', ' ', 'b', 'o', 'd', 'y']
```

Is there something that doesn't capture that your function / class does?

Supposing `chain` doesn't quite fit the bill, I prefer the class-based version's implementation. However, I think you can avoid needing to prime the generator function with the [coroutine decorator](http://dabeaz.com/coroutines/coroutine.py). That still has an issue with the empty iterator case, though.

**Comment by erikrose** [comment]
> prime the generator function with the coroutine decorator.

Independently invented [here](https://github.com/erikrose/more-itertools/blob/master/more_itertools/more.py#L276) as `consumer` :-)

**Comment by erikrose** [comment]
Incidentally, if chain doesn't work out for some reason, this also reminds me of a `peekable` whose buffer is pre-loaded with the things you want prepended.

**Comment by bbayles** [comment]
Hm, good idea:
```python
>>> from more_itertools import peekable
... 
... iterable = [1, 2, 3]
... it = peekable(iterable)
... it._cache.appendleft(0)
... list(it)
[0, 1, 2, 3]
```

The `peekable`-wrapped iterable has a `_cache` attribute that can be manipulated for this purpose. I suppose we could add a method that exposes this normally-hidden attribute?

```python
>>> from more_itertools import peekable
... 
... class peekable_2(peekable):
...     def prepend(self, *items):
...         self._cache.extendleft(reversed(list(items)))
... 
... iterable = [1, 2, 3]
... it = peekable_2(iterable)
... it.prepend('a', 'b', 'c')
... list(it)
['a', 'b', 'c', 1, 2, 3]
```

**Comment by erikrose** [comment]
I did think of one situation in which that might be preferable to chain. Itertools routines turn straight into C stack frames, which means 8k of them will overflow the stack. I've actually had that happen to me. So, if you're doing a LOT of nested chain calls, peekable would scale better.

**Comment by diazona** [comment]
Yeah, the situation that prompted me to suggest this is a text-parsing application which has to work on 10 million lines of text, and I wind up pushing a few things every 10 lines or so. Repeated calls to `chain` would definitely overflow the stack.

Using `chain` also cuts off the possibility of using `for` loops, like
```python
for chunk in iterable:
    # process part of chunk
    iterable.send(rest_of_chunk)
```
I'm certainly not claiming that this behavior is _impossible_ to do with existing tools, I just think having a dedicated pushback iterator makes the resulting code a lot cleaner.

I do really like your idea of using the cache in `peekable`. I didn't even think to look at that, but now that I do, `peekable` is implemented almost the same way that I did `pushback`. It seems like a natural and straightforward change to add a `send()` method (or `prepend()` or `push()` or `pushback()` or whatever you like) to `peekable`. I'll try working that up into a patch and testing it to see if there are any complications.

Irrelevant side note: `peekable` is the reason I started using this library, and still my most commonly used more-itertool by far.

**Comment by diazona** [comment]
Quick update: @bbayles, adding the method you suggested a few comments back to `peekable` seems to work perfectly. It passes all my tests for `pushback`, anyway, except the ones associated with `maxlen`, and that was a low-priority feature anyway.

The one change I'd want to consider is whether to use `reversed()` or not. To me, it seems more natural that `p.prepend(a, b, c)` should be equivalent to

    p.prepend(a)
    p.prepend(b)
    p.prepend(c)

which would cause the elements to be returned by `next()` in the order `c`, then `b`, then `a`. To make it work out that way, we need to not use `reversed()`. It would be just

    def prepend(self, *items):
        self._cache.extendleft(items)

I can just as well see the case for using `reversed()`, so I wouldn't object to it, it's just not something to come down on one way or the other without thinking about it.

**Comment by bbayles** [comment]
Thanks for checking. My thought was that the user need not know we're using a `deque` underneath the hood, so users would have no need to know that `extendleft` ordering rules apply.

If you're up for making a pull request to give a `prepend` method to `peekable`, I'd be inclined to merge it based on  [this comment](https://github.com/erikrose/more-itertools/issues/106#issuecomment-272726366).

**Comment by erikrose** [comment]
I could go either way on ordering. `prepend(a, b, c)` meaning…

```python
prepend(c)
prepend(b)
prepend(a)
```

…is nice because it's like (a, b, c) + (q, r, s, ...) and works with my visual intuition. I also like the name "prepend"; it calls to mind `list.append`. There could be practical benefits to making it behave like `deque`, especially if we name the routine `appendleft` or `extendleft` and tweak the behavior so it can be a drop-in replacement. My leaning, though, is that it won't be used as a drop-in for `deque` much; if you can use a deque, you should probably keep using a deque.

**Comment by pylang** [comment]
Just a comment: I like the term `prepend`.  `prepend` is more clear to me than `pushback` in light of a recent application:

Since all primes are odd, except the number 2, make  sequence of primes by adding 2 to a sequence of odd primes:
```python
import itertools as it

def prepend(iterable, prefix):
    """Return an iterator prepended with a prefix."""
    return it.chain(prefix, iterable)

odd_primes  = [3, 5, 7, 11, 13, 17, 19, 23, 29, 31] 
list(prepend(odd_primes, [2]))
# Out: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31]
```

So I think prepending a generator would be useful.

**Comment by diazona** [comment]
@pylang In cases like that, where you know what you'd be prepending before you start iterating, `chain()` is perfectly suited. I'm envisioning `prepend()` for cases where that's not the case - you only obtain the things to prepend _after_ you started iterating.

**Comment by diazona** [comment]
I've made the pull request, but as is it doesn't use `reversed()`, so in its current state `p.prepend(a, b, c)` is equivalent to
```python
p.prepend(c)
p.prepend(b)
p.prepend(a)
```
I'm definitely open to changing that, I just sent in the pull request as it is because that's how I'd implemented it.

One more thing to consider: if someone fully iterates through a `peekable` and gets a `StopIteration` from `next()`, should future calls to `next()` raise `StopIteration` even if `prepend()` was called in the interim? For example:
```python console
>>> p = peekable(range(3)); list(p); next(p)
StopIteration:
>>> p.prepend(10)
>>> next(p)
```
Does this last call to `next()` raise `StopIteration`? (And if so, should the preceding call to `prepend()` raise an exception too?) I'm thinking not, since it makes sense that when you prepend an element, you expect to get that element from `next()`, period. This would also be consistent with the `chain()` reassignment suggested earlier. But I don't know of any other case where an iterator that has previously produced a `StopIteration` exception can be "reactivated" to return something from `next()`. In the pull request I implemented it in the former way, consistent with `chain()`.

**Comment by diazona** [comment]
And... there are some CI failures. :-( I will fix that.

**Comment by bbayles** [comment]
Re: ordering, I think we should go with "order passed in is the order you get out." You can always prepend single items in a loop if you want that behavior.

Re: post-exhaustion behavior, I think if you prepend an item, the iterator should yield it on the following `next` call, as you have currently.

Re: do we need a `prepend()` itertool? I think no; I rejected the same [here](https://github.com/erikrose/more-itertools/pull/22#issuecomment-258646022).

Thanks for the PR! I'll check it out once your tests are in order.

**Comment by diazona** [comment]
@pylang I just realized I may have missed the point of your comment before. If you meant that it would be useful to pass an iterable (e.g. a generator) to `prepend()` rather than giving the arguments individually, you can already do that using argument unpacking. A few of the test cases for `prepend()` use this, e.g.
```python
it = peekable(range(5))
it.prepend(*range(20000))
actual = list(it)
expected = list(chain(range(20000), range(5)))
eq_(actual, expected)
```
Of course my previous point stands that if you know what you're prepending before you start iterating, you should just use `chain()` because that's exactly what it's there for.

@bbayles I assume that when you say you don't need a `prepend()` itertool, you're talking about the latter case, the one that can be trivially implemented by `chain()`?

Anyway, I've fixed the test errors and reversed the direction in which multi-argument `prepend()` operates.

It occurred to me that it would be easy to add a keyword argument which allows the caller to specify the direction. With the current implementation, prepending in LIFO order needs to be done with an explicit call to `reversed()` instead, i.e. `p.prepend(*reversed(it))`. Then because `prepend()` also calls `reversed()`, I think we wind up doing something akin to `reversed(tuple(reversed(it)))`. It's possible that this may impact performance in some cases, compared to avoiding any calls to `reversed()` at all (which could be done with a keyword argument), but I imagine those cases would be rare to nonexistent, so I didn't add it.

**Comment by bbayles** [comment]
Re: `prepend()` itertool, you're right. No need to make a trivial wrapper around `chain()`.

Re: keyword argument, I think no. I think the question of ordering has only come up because my sample implementation used `*args` to allow prepending multiple values, yeah? It wasn't in the original description; just an easy-to-add bonus.

**Comment by erikrose** [comment]
When it looks good to you, Bo, it looks good to me.

**Comment by bbayles** [comment]
Thanks again, @diazona; looking forward to your next suggestion.
