### ISSUE TITLE
Tool suggestion: identify elements adjacent to those matching a predicate

### ISSUE THREAD

**Issue by diazona** [erikrose/more-itertools#109]
I just came up with another function that I don't _think_ already exists and might make a useful addition to more-itertools: identifying elements in an iterable that match a predicate or are adjacent to those matching a predicate. As a stupid (but simple) example, suppose I want to detect which letters are vowels or adjacent to vowels in a word. The design I have in mind returns a tuple for each element in the iterable with a boolean indicating whether it is or is adjacent to a "selected" element, as well as the element itself.
```python console
>>> list(adjacent(lambda c: c in 'aeiou', 'thursday'))
[(False, 't'), (True, 'h'), (True, 'u'), (True, 'r'), (False, 's'), (True, 'd'), (True, 'a'), (True, 'y')]
```
In my application it's important to know where the (equivalents of the) vowel-centered groups end and begin, in addition to knowing which elements are in those groups, so I pass the result of `adjacent()` through `groupby()`. (This is akin to choosing context lines in a differ.) If I wanted an iterable of just `['h', 'u', 'r', 'd', 'a', 'y']` in that example, I could use instead use `filter()` and `map()` or a generator, i.e. `(e[1] for e in adjacent(...) if e[0])`. I think this flexibility is important.

The question I want to bring up before sending in a pull request is how to generalize this. My base implementation is the following:
```python
def adjacent(predicate, iterable):
    i1, i2 = tee(iterable)
    selected = chain([False], map(predicate, i1), [False])
    adjacent = map(any, windowed(selected, 3))
    return zip(adjacent, i2)
```
(designed to avoid calling `predicate()` more than once per item) It's easy enough to change the number of elements of "context" by increasing the second argument to `windowed()`, and that would be a straightforward generalization. Is it also worthwhile to support arbitrary "masks" by using `stagger()` instead of `windowed()`? E.g. passing `offsets=(-1, 1)` to "mark" only elements which are before or after those which satisfy the predicate, leaving out the ones which do satisfy the predicate themselves? Or `offsets=(0,1,2)` to "mark" items which satisfy the predicate and the two that follow them?

**Comment by bbayles** [comment]
My first impression was that this was a straightforward application of `windowed`. However, after playing with it for a bit in the interpreter, I couldn't come up with a more elegant method than yours; this is tricky to get right without calling `predicate` more frequently.

So, I'm open to a PR for this. For generalizations, I'm good with an optional `n` argument (I guess verify that it's at least 3?).

**Comment by diazona** [comment]
Yeah, sounds like you went through the same thought process I did. It seemed easy at first but was not so straightforward to get right. I'll get that PR started shortly.

Incidentally, I wonder if there's a use for a "companion" itertool which combines the `(bool, item)` pairs into groups. I expect a common, if not the most common, use case for `adjacent()` is to iterate over groups of items which are within a given distance of one that satisfies the predicate; this would be used in generating a contextual diff, for example, and it's also how I use it in the application that inspired me to come up with this algorithm. But the logic to convert the `(bool, item)` pairs into groups is itself a little messy, because we don't want to `bool` to appear in the group. Here's what I've come up with:
```python
def adjacent_groups(predicate, iterable):
    for key, group in groupby(adjacent(predicate, iterable), lambda t: t[0]):
        yield (key, (t[1] for t in group))
```
Come to think of it, this could be generalized into another itertool, basically a `groupby()` wrapper that allows the user to customize what appears in the group as well as what is used for the key.
```python
def better_groupby(iterable, keyfunc=None, valuefunc=None):
    for key, group in groupby(iterable, keyfunc):
        yield key, map(valuefunc, group)
```
Then `adjacent_groups()` could just be implemented as
```python
better_groupby(adjacent(predicate, iterable), lambda t: t[0], lambda t: t[1])
```
(or with `operator.itemgetter()`). I'm not sure if this warrants inclusion in more-itertools, since it's not hard to do on a case-by-case basis, but personally I would find it really handy to have this function available for code readability, if nothing else. And even if you don't want the generic `better_groupby()` as an itertool (under a different name of course), I think there is a good case for something like `adjacent_groups()` simply because of how common I expect that usage to be.

**Comment by bbayles** [comment]
I'm positive on `better_groupby` (maybe `groupby_transform`?), but I'd say leave `adjacent_groups` as an exercise for the reader?
