### ISSUE TITLE
more_itertools.collate is too similar to heapq.merge

### ISSUE THREAD

**Issue by kmike** [erikrose/more-itertools#11]
Hi there,

Nice idea to create more_itertools package! But it seems more_itertools.collate is duplicating heapq.merge from standard library with minor differences. Do you really need it?

**Comment by julianpistorius** [comment]
Update: Python 3.5 added `key` and `reverse`:

https://docs.python.org/3/library/heapq.html#heapq.merge

Thankfully `more-itertools` is there for those of us stuck in 2.7 land. :)

**Comment by bbayles** [comment]
I like the "call out to `heapq.merge()` if we can" method; I'll do that in a PR soon (1274fe20b6234df3917dfe3748399a36c431bebc).

**Comment by bbayles** [comment]
Fixed in #69. Thanks @kmike and @julianpistorius !
