### ISSUE TITLE
Consider making side_effect(file_obj=) arg more generic

### ISSUE THREAD

**Issue by erikrose** [erikrose/more-itertools#114]
Closing a file after yielding its last line is all well and good, but I wonder: can we be more general and add power without losing much brevity?

```python
side_effect(log, some_file, last=lambda: some_file.close())
```

```python
side_effect(ingest, listdir(some_dir), last=lambda: rmtree(some_dir))
```

@bbayles? @yardsale8?

**Comment by bbayles** [comment]
Hmm, interesting.

(1) This makes me think that at the minimum we should change the documentation (and maybe the argument name) to be more generic - it works for anything that needs to be closed, not just file objects.

(2) it does seem like files are a justifiably special case with `side_effect`, since writing to a file is the quintessential "impure" activity.

(3) Adding a generic "do this thing after you're done `side_effecting` the iterable items" opens the door to "do this thing _before_ you start `side_effecting` the iterable items," which seems like it might be a bridge too far? The goal here is to make it easy to do something common (close a file) that's awkward to do currently (you'd have to wrap your whole pipeline in a `with` block), not to let you put more things on a line (this was my initial resistance to #112 ). 

I'll look at the language for (1) and noodle around with (3).

**Comment by bbayles** [comment]
I thought the "well if you want to run a generic function after, why not before" was a reductio ad absurdum, but now that I've implemented it I kind of like it? See #115.

**Comment by erikrose** [comment]
I came to the same conclusion moments after my head hit the pillow: why not do `before` also? It took another 30 seconds from there to "Why not just have it take a context manager?" From there, I landed back at `with_iter`. In fact, I still am failing to see why #112 couldn't have just been written as…

```python
consume(print(x, file=output) for output in with_iter(open("temp.tmp","w")) for x in range(3)).
```

**Comment by yardsale8** [comment]
I am with Eric on the fact that we are basically reinventing context management.  Eric's suggestion was one of the first I tried, but it fails.

``` python
In [1]:  [print(x, file=out) for out in with_iter(open('temp.tmp', 'w')) for x in range(3)]
(snip)
    342     with context_manager as iterable:
--> 343         for item in iterable:
    344             yield item
    345

UnsupportedOperation: not readable
```

**Comment by bbayles** [comment]
Right, `with_iter()` would be fine for reading from a file that's the source for our iterable, but in Erik's example `range()` is the source.

`contextlib.closing()` almost does what we want, but not quite.

At this point I like the `before` and `after` things, so I'm inclined to merge that. But I'd be interested if there's something more we might stumble onto in this discussion.

**Comment by bbayles** [comment]
I could see divorcing this from `side_effect()` and re-introducing `with_file()` with a different name and explanation. Instead of re-inventing context management we'd just be using it.

```python


def contextualize(obj):
    """Wrap an *obj*, an object that supports the context manager protocol,
    in a ``with`` statement and then yield the resultant object.

    The object's ``__enter__()`` method runs before this function yields, and
    its ``__exit__()`` method runs after control returns to this function.

    This can be used to operate on objects that can close automatically when
    using a ``with`` statement, like IO objects:

        >>> from io import StringIO
        >>> from more_itertools import consume
        >>> it = [u'1', u'2', u'3']
        >>> file_obj = StringIO()
        >>> consume(
        ...     print(x, file=f) for f in contextualize(file_obj) for x in it
        ... )
        >>> file_obj.closed
        True

    """
    with obj as context_obj:
        yield context_obj

```

**Comment by yardsale8** [comment]
Here's a thought.  `side_effect` could be generalized to take 1 or 2 (maybe more) sequences and a function with a matching number of arguments.  Then you have a clean composition with `contextualize` defined above.

``` python
consume(side_effect(lambda file, x: print(x, file=file), contextualize(open('temp.tmp','w'), xs))
```
To make this work, the iteration would need to be a double loop (Cartesian product), equivalent to

``` python
(func(x,y) for x in xs for y in ys)
```

I am not sure how you would generalize the chunking in side-effect.  Perhaps a list of chunk-sizes when there is more than one sequence?

**Comment by bbayles** [comment]
Hmm, I see what you mean, but I'm not sure we should go there... :dragon_face:

I think we should pick between #115 (`before` and `after` functions for `side_effect()`) and a re-worded #112 (`with_file()`, but with a different name and explanation). I'll let Erik say which one he likes best?

---

__#115 Pros__: `before` and `after` functions work nicely for setup and shutdown tasks. This is more flexible than what's currently in `master` (`file_obj` keyword), and it's easy to imagine how even the `before` function could be useful (see the write-a-header examples).

__#115 Cons__: Basically re-invents context management - `before` is `__enter__`; `after` is `__exit__`.

__#112 Pros__: Could be used places other than `side_effect()`. Fills what I think is a gap in `contextlib` - a function that makes sure `__enter__` gets called, yields, and then makes sure `__exit__` gets called.

__#112 Cons__: Not all that itertools-y?

**Comment by yardsale8** [comment]
I just realized that I can get the desired effect from my last example without rewriting `side_effect` using `product` from itertools (of course there is an itertool for this ... duh).

``` python
consume(side_effect(lambda f, x: print(x, file=f), product(contextualize(open('tmp.tmp','w')), xs))
```
Does this example make `contextualize` feel more like an `itertools` tool?  

I personally like that I can do this without holding a reference to the file handler, allowing the side-effect to be defined and consumed in the one expression.  This would be my one knock on the current solution, `before` and `after` require that I hold an external reference to the `file`, which might as well come from a `with` statement.   

Unfortunately, the expression using `product` and `contextualize` is pretty complicated and obtuse, not the sort of thing I would like to present to my students.

What if `with_file\contextualize` acted like `product(contextualize(f), xs)`, sort of a context zip?

``` python
def contextzip(context, seq):
    with context as c:
        for item in seq:
            yield (c, item)
```

This allows the user to bundle a context manager with the items of the sequence.  They could do what-ever is required with the pair, assured that the context manager will be processed correctly behind the scenes.

Then the log to a file example becomes

``` python
consume(side_effect(lambda f, x: print(x, file=f), contextzip(open('temp.tmp','w'), xs)))
```

**Comment by erikrose** [comment]
Thank you both for thinking through all this in such depth! I really like `contextualize`. If we rename it `context`, look how nicely callsites read:

```python
    @contextmanager
    def fake_file():
        """Pretend we're opening and closing a file."""
        print('open')
        yield 'some_file'
        print('close')

--> [print(x, c) for c in context(fake_file()) for x in range(3)]
```
```
open
0 some_file
1 some_file
2 some_file
close
```

The simpler `context()` + genexprs should be able to fill the role of `contextzip`, plus you can use arbitrarily many context managers by adding more `in` clauses.

I am still thinking about whether `before=` and `after=` kwargs are a good idea on `side_effect()`.

**Comment by erikrose** [comment]
`side_effect()`'s `before` and `after` are expressible using `context()`, assuming they are already conveniently encapsulated in a context manager:

```python
[x for c in context(fake_file())
   for x in side_effect(lambda x: print('logging: ', x * 2, c), range(3))]
```

That works even with Python 3's tighter list comprehension scoping. (As before, you have to be careful to put your context manager in the first `in` clause, or it opens and closes repeatedly.)

If the open/close behavior you're looking for is *not* in a context manager, it gets wordy. In that case, before/after are certainly a win on conciseness and arguably on clarity as well. Given that the original use case was logging to a file, I think we should merge `context()` and then wait to see if a common need for non-context-manager before/after hooks on `side_effect()` emerge. If they do, we can merge #115 also as a convenience.

**Comment by yardsale8** [comment]
I think you're right, `context` is simple and provides the most flexibility.

**Comment by bbayles** [comment]
I'm good with this outcome; I'll back off the `file_obj` addition to `side_effect()` and put out a  PR for `context()`. I'll also close #115 pending evidence of its usefulness.

**Comment by bbayles** [comment]
That's #118. I think ready for a release after that? I have a branch mostly ready for that with some cleanup.

**Comment by erikrose** [comment]
Great! Thanks, @bbayles and @yardsale8!
