### ISSUE TITLE
ilen() is slow

### ISSUE THREAD

**Issue by wbolster** [erikrose/more-itertools#116]
you may want to steal the `cardinality.count()` implementation from
https://github.com/wbolster/cardinality  ;)

**Comment by bbayles** [comment]
Ha, thanks - I know that `consume` uses a similar trick. Switching to the length-1 deque saves ~1% on my machine. Will go in with PR #117.

**Comment by wbolster** [comment]
speed increase depends on what you are iterating over. :)

and for things that have `__len__()` this brings it from O(n) to O(1) which can be a massive speedup.

**Comment by bbayles** [comment]
Fixed in PR #117; many thanks.
