### ISSUE TITLE
`roundrobin` vs. `interleave_longest`

### ISSUE THREAD

**Issue by pylang** [erikrose/more-itertools#122]
Recently while looking at the recipes, I noticed  [`robinrobin`][1] gives similar results to [`interleave_longest`][2]:

```python
import more_itertools as mit

iterables = ['ABC', 'D', 'EF']

list(mit.roundrobin(*iterables))
# ['A', 'D', 'E', 'B', 'F', 'C']

list(mit.interleave_longest(*iterables))
# ['A', 'D', 'E', 'B', 'F', 'C']
```

I realize `interleave_longest` was discussed among other items in #22, but it seems it's similarity to an existing recipe may have been overlooked.  Is there a rationale for keeping both tools?  

  [1]: https://github.com/erikrose/more-itertools/blob/master/more_itertools/recipes.py#L256-L275
  [2]: https://github.com/erikrose/more-itertools/blob/master/more_itertools/more.py#L701-L711

**Comment by bbayles** [comment]
Yes, I think they produce equivalent output - this was an oversight; if I'd realized it I would have made `interleave()` say "For a version that doesn't terminate on the shortest iterable, see `recipes.roundrobin()`" or something.

I might add a note to `interleave_longest()`'s docstring to say it's an alternate implementation of `roundrobin()`... I think it's a much better one.

**Comment by pylang** [comment]
I agree `interleave_longest` is a more pythonic implementation than the `roundrobin` recipe.  A quick profile suggests it seems to be about 2x faster too.  A more thorough performance comparison may further justify keeping it.

**Comment by bbayles** [comment]
I'll get 3a88f59523e0992320644ea8e26c1cbf11aae197 in the next release, which clarifies the situation.

**Comment by bbayles** [comment]
Situation clarified in the docs; thanks @pylang .
