### ISSUE TITLE
add empty or has method to peekable class

### ISSUE THREAD

**Issue by apatrushev** [erikrose/more-itertools#124]
Usually it is good to check have you anything in peekable as part of more complex checks.
For example:
```python
while p.peek(None) is not None and p.peek().type == 1:
```
Will be shorter and more readable as:
```python
while not p.empty() and p.peek().type == 1:
```
or even:
```python
while p.has() and p.peek().type == 1:
# === variant
while p.more() and p.peek().type == 1:
```

**Comment by bbayles** [comment]
`peekable` objects have a `__bool__` method. Shouldn't you be able to do this?
```python
while p and whatever():
    pass

while (not p) or something():
    pass
```

Hope that helps.

**Comment by apatrushev** [comment]
Sorry, I was inattentive while reading the docs.
