### ISSUE TITLE
Combine peekable with spy

### ISSUE THREAD

**Issue by WilliamRusnackAtFord** [erikrose/more-itertools#129]
I like how peekable can look ahead and modify without affecting it's iterator and I like how spy can look ahead more than one.

It would be really nice if I could specify how many I want to look ahead with peek.

```python
>>> a = peekable((1,2,3,4,5))
>>> a.peek(2)
2
```

**Comment by bbayles** [comment]
Thanks for the writeup. I think that the slicing support for `peekable` does what you like?

```python
>>> from more_itertools import peekable
... a = peekable([1, 2, 3, 4, 5])
>>> a[1]
2
>>> a[:2]
[1, 2]
```

**Comment by WilliamRusnackAtFord** [comment]
Thanks. I'll start reading further down.
