### ISSUE TITLE
Installation and examples in README

### ISSUE THREAD

**Issue by pylang** [erikrose/more-itertools#130]
I suspect the README is the first (and often the only) stop from visitors to most packages.  Through the visitor's lens, I observe the following:

First, it's actually not clear how to install the package (from either the README or the docs).  I propose **adding a line on installation to the README**.

...
## Installation
    > pip install more_itertools
...

Second,  right now the first tool in the API docs is the new `more_itertools.adjacent`, which has a heavier docstring than traditional ones.  IMO, seeing this much text for the first tool is less inviting to newcomers trying to quickly figure out what this package does.  I suggest **adding a couple elegant examples to the README**, maybe a recipe and original, e.g. `flatten` and `chunked`.  

...
## Examples

```python
>>> import more_itertools as mit

# Itertools Recipe
>>> list(mit.flatten([[0, 1], [2, 3]]))
[0, 1, 2, 3]

# More-Itertools Original
>>> list(mit.chunked([1, 2, 3, 4, 5, 6, 7], 3))
[[1, 2, 3], [4, 5, 6], [7]]

```
...

The idea is to succinctly demonstrate up front that this package is a simple extension of `itertools`, and it is easy to use.

**Comment by erikrose** [comment]
These sound like sane suggestions to me. In particular, it's probably time for us to divide our routines into categories to make the docs more approachable; there are rather a lot of them now!

**Comment by bbayles** [comment]
Good suggestion - I've thought the same about the ordering of the docs recently. I'll take a run at this shortly.

**Comment by bbayles** [comment]
- [ ] Update the README with installation instructions and examples (PR #131)
- [ ] Similarly update `docs/index.rst`
- [ ] Look at categorizing the functions

**Comment by bbayles** [comment]
Here is my proposed grouping and ordering for the docs, with easy-to-grok functions listed first:

---
Grouping - routines that yield groups of items from an iterable:
* chunked
* sliced
* distribute
* divide
* split_before
* split_after
* bucket

Lookahead - routines that peek at an iterable's values:
* spy
* peekable

Windowing - routines that yield windowed data
* windowed
* stagger

Augment - routines that augment an itertable's items with additional data:
* adjacent
* count_cycle
* groupby_transform
* intersperse
* padded

Combine multiple - functions that combine multiple iterables:
* collapse
* sort_together
* interleave
* interleave_longest
* collate
* zip_offset

Summarization - functions that return data derived from an iterable:
* ilen
* first
* one
* unique_to_each

Others:
* numeric_range
* side_effect
* distinct_permutations
* always_iterable
* iterate
* consumer
* with_iter

---

I considered the categories in the `itertools` docs, but it's pretty hard to fit ours into those. I'd like to feature `distinct_permutations` and `numeric_range` more prominently (the former is a helpful combinatoric generator missing from the standard library; the latter is commonly done incorrectly), but I thought it best not to have a "group" of one.

**Comment by bbayles** [comment]
(Added recipes to the groupings above)

**Comment by pylang** [comment]
Just adding to the proposals.

Recipes

| Function | Category |Result|
|:-|:-|:-:|
|`take`                               | access    | `list` |
|`tabulate`                           | transform | `map` |
|`tail`                               | access    | `deque` |
|`consume`                            | access    | `None` |
|`nth`                                | access    | element |
|`all_equal`                          | test      | `bool` |
|`quantify`                           | aggregate | `int` |
|`padnone`                            | transform | generator |
|`ncycles`                            | transform | generator |
|`dotproduct`                         | transform | number |
|`flatten`                            | join      | `list` |
|`repeatfunc`                         | transform | generator |
|`pairwise`                           | group     | generator |
|`grouper`                            | group     | generator |
|`roundrobin`                         | arrange   | generator |
|`partition`                          | partition | generator |
|`powerset`                           | arrange   | generator |
|`unique_everseen`                    | access    | genreator |
|`unique_justseen`                    | access    | genreator |
|`iter_except`                        | access    | generator |
|`first_true`                         | access    | element |
|`random_product`                     | arrange   | `tuple` |
|`random_permutation`                 | arrange   | `tuple` |
|`random_combination`                 | arrange   | `tuple` |
|`random_combination_with_replacement`| arrange   | `tuple`|


Originals

| Function | Category |Result|
|:-|:-|:-:|
|`bucket`               | partition | generator |
|`chunked`              | group     | generator |
|`collapse`             | join      | generator|
|`collate`              | arrange   | generator |
|`consumer`             | arrange   | decorator |
|`distinct_permutations`| arrange   | generator |
|`first`                | access    | element |
|`ilen`                 | aggregate | `int` |
|`interleave`           | join      | generator |
|`interleave_longest`   | join      | generator |
|`intersperse`          | join      | generator |
|`iterate`              | transform | generator |
|`one`                  | access    | element |
|`peekable`             | slice     | generator |
|`side_effect`          | transform | generator |
|`sliced`               | slice     | generator |
|`split_after`          | partition | generator |
|`split_before`         | partition | generator |
|`spy`                  | slice     | generator |
|`unique_to_each`       | slice     | `list` |
|`windowed`             | slice     | `None` |
|`with_iter`            | misc.     | generator |
|`padded`               | join      | element |
|`distribute`           | arrange   | `list` |
|`sort_together`        | arrange   | `list` |
|`stagger`              | group     | `zip` |
|`zip_offset`           | group     | `zip` |
|`adjacent`             | group     | generator |
|`groupby_transform`    | group     | generator |
|`divide`               | partition | generator |
|`always_iterable`      | transform | `tuple` |
|`numeric_range`        | misc.     | generator |


Categories

- access
- transform
- test
- aggregate
- join
- group
- arrange
- partition
- slice
- misc.

**Comment by erikrose** [comment]
If I had to pick one vocab, I find the [initial one](https://github.com/erikrose/more-itertools/issues/130#issuecomment-300355734) fits my brain better. It might just be that the descriptions following the titles clarify the meanings for me; I like those. For the final thing, I'd want to make sure we stick with a consistent part of speech, e.g. summariziation→summarizing, augment→augmenting. Nice work, both of you! Thanks for whipping our docs into shape!

**Comment by bbayles** [comment]
[This branch](https://github.com/erikrose/more-itertools/blob/api-categorization/docs/api.rst) has a preview at how the categorization might look. I'm not sure about the way I'm splitting the new and old routines, but I do like having the categories available in the table of contents.

**Comment by bbayles** [comment]
Will refine some of this later, but I think we've made some improvements here. Thanks!
