### ISSUE TITLE
numeric_range with one argument

### ISSUE THREAD

**Issue by MSeifert04** [erikrose/more-itertools#136]
Is there any use-case for `numeric_range` with only one argument? It seems the type of the objects that are returned are solely depending on the `type` of `start` and `step`. 

When only `stop` is given (even if I use `float`s or `Decimal` as `stop`) it will always return integers. And it's a lot slower than `range`.

**Comment by bbayles** [comment]
The one-argument form is there to match the way `range` works.

Does PR #137 resolve this? I agree if you pass in a `float` you should probably get `floats` back.

**Comment by MSeifert04** [comment]
Yes #137 would resolve the question about the use-case. It makes it a bit unpredictable though (see comment on the PR).

I actually just wondered why there's a 1-argument form at all, wouldn't `numeric_range(start, stop, step=1)` be better - it makes the function a lot easier and the result type is always defined by the `start` argument (easier documentation)?

**Comment by bbayles** [comment]
Re: 1-argument version existence, again, wanted to match `range`. I'd rather not break the API and do a major version release to change it.

**Comment by MSeifert04** [comment]
Oh, I didn't realize you already released `numeric_range`.

**Comment by bbayles** [comment]
Oh, maybe I haven't yet... Either way, I want to match `range()`.

**Comment by MSeifert04** [comment]
Yes, with #137 there's also a convincing use-case for it 👍

**Comment by bbayles** [comment]
Thanks for the careful examination of this; hope to see more!
