### ISSUE TITLE
Functional Programming

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [erikrose/more-itertools#142]
I've been looking for a good python functional programming library for a while now. [PyFunctional](https://github.com/EntilZha/PyFunctional) is an ok start but is lacking a lot of features that I would expect from a functional library. Most importantly it does not make reusable pipes meaning combined functions cannot be used more than once, which isn't good if the pipe is going to be used a lot.
Do you know of any libraries that do allow reusable pipes?
I also think that the functionality of more-itertools would be amazing if we could add them to the PyFunctional package or do something similar.
Let me know what you think!

**Comment by pylang** [comment]
@BebeSparkelSparkel I am not clear on this term "resusable pipes".  Could you demonstrate an example of the behavior you'd be interested in seeing?

**Comment by BebeSparkelSparkel** [comment]
There is a package [pyfunctional.org](http://www.pyfunctional.org/) that tries to make python more functional.
It has the problem of having to rebuild all the function chains every time data needs to be processed through them. I would like to be able to keep the chain and run new data through it.

I would like to be able to do things like:

```python
>>> transform = Pipe()\
...     .map(lambda x: x * 2)\
...     .filter(lambda x: x > 4)\
...     .reduce(lambda x, y: x + y)
>>> transform(1, 2, 3, 4)
14
>>> transform(5, 6, 7)
36
```

**Comment by pylang** [comment]
> rebuild all the function chains every time data needs to be processed 

I'm not entirely sure what you mean by this.  Is what your looking for different than a normal function?
```python
import functools as ft

def transform(*seq):                                       # *[1, 2, 3, 4]
    a = map(lambda x: x * 2, seq)                          # [2, 4, 6, 8]
    b = filter(lambda x: x > 4, a)                         # [6, 8]
    c = ft.reduce(lambda x, y: x + y, b)                   # 14
    return c
    
transform(1, 2, 3, 4)
# 14

transform(5, 6, 7)
# 36
```

**Comment by bbayles** [comment]
I like the aesthetics of the chains, but I'm not really up for introducing a class that re-implements all the routines (or tries to create them automagically). I like pylang's two examples for re-usable processing pipelines. See also [this SO answer](https://stackoverflow.com/a/38755760/353839).

So I think I'll close this answer, but will encourage further discussion of these ideas - thanks!

**Comment by BebeSparkelSparkel** [comment]
I'm still developing it but I have been working on the class that you mentioned. [github.com/BebeSparkelSparkel/functional_pipes](https://github.com/BebeSparkelSparkel/functional_pipes)

**Comment by BebeSparkelSparkel** [comment]
@bbayles and @pylang I've gotten the [functional_pipes](github.com/BebeSparkelSparkel/functional_pipes) coded and would like your opinion of its functionality if possible.

**Comment by bbayles** [comment]
Would be great if you posted some examples of how to do things like you proposed [here](https://github.com/erikrose/more-itertools/issues/142#issuecomment-303918553)?

Closing this issue for now, but happy to link to your project if you post it to PyPI.

**Comment by BebeSparkelSparkel** [comment]
Had a conference last night. Just pushed example.py
