### ISSUE TITLE
ReST on PyPI page not rendering

### ISSUE THREAD

**Issue by erikrose** [erikrose/more-itertools#143]
https://pypi.python.org/pypi/more-itertools/ is showing the raw restructured text source code, not rendered HTML. Maybe a syntax error somewhere?

**Comment by erikrose** [comment]
No, syntax seems fine, according to rst2html.py.

**Comment by erikrose** [comment]
Ah, it's probably the `automodule` directive in versions.rst being unrecognized.

**Comment by bbayles** [comment]
It actually seems to be the `:func:` directives in the Version History section. I've edited the PyPI page manually to fix so I don't have to do a release.

It's a bummer to not have automatic links to the docs from the What's New page, but I'll take them out for next time.

**Comment by erikrose** [comment]
I took care of the :func: calls as well in my patch.

**Comment by bbayles** [comment]
Thanks! I'll make sure to double check for the next release.
