### ISSUE TITLE
Intersperse every n items

### ISSUE THREAD

**Issue by pylang** [erikrose/more-itertools#151]
From [this SO post][1], given 

```python
number = 123456789012345678901234567890
expected = "12345 67890 12345 67890 12345 67890"
```

This looks like an opportunity for `interspearse`.  However, the present implementation "injects" (actually zips) one unique element between every element of the iterable.  I propose modifying `interspearse`  to inject an element between every n elements, e.g. a space every 5 characters in the `expected` string.

Here is a quick modification to  [the `intersperse` code][3] adding an `n` keyword argument:

```python
import itertools

import more_itertools as mit


def intersperse(e, iterable, n=1):
    it = iter(mit.chunked(iterable, n))                    # dependency 
    filler = itertools.repeat(e)         
    zipped = mit.collapse(zip(filler, it))                 # dependency
    next(zipped)
    return zipped
```

Results

```python
print(list(intersperse('x', 'ABCD')))
print(list(intersperse('x', 'ABCD', 2)))
# ['A', 'x', 'B', 'x', 'C', 'x', 'D']
# ['A', 'B', 'x', 'C', 'D']


print(list(intersperse(None, [1,2,3])))
print(list(intersperse(None, [1,2,3], 2)))
# [1, None, 2, None, 3]
# [1, 2, None, 3]

print("".join(intersperse(" ", str(number), 5)))
# 12345 67890 12345 67890 12345 67890

```
These are minor changes, i.e. adding `chunked` and substituting `flatten` with `collapse`.  The downside is that this modified implementation depends on other tools.  I imagine the hope is to keep new recipes independent.   Before proceeding, are there any thoughts on adding a keyword, suggestions for a different implementation or desire to keep as is?

Related posts
- [Insert element in Python list after every nth element][5]
- [Pythonic way to insert every 2 elements in a string][6]
- [How do I insert a space after a certain amount of characters ...][8]
- [Python - How to add space on each 3 characters?][7]
- [Merge lists in Python by placing every nth item ...][2]

[1]: https://stackoverflow.com/questions/21196761/python-how-to-print-space-per-nth-char/21197057#21197057
[2]: https://stackoverflow.com/questions/34692738/merge-lists-in-python-by-placing-every-nth-item-from-one-list-and-others-from-an
[3]: https://github.com/erikrose/more-itertools/blob/master/more_itertools/more.py#L498
[5]: https://stackoverflow.com/questions/31040525/insert-element-in-python-list-after-every-nth-element
[6]: https://stackoverflow.com/questions/3258573/pythonic-way-to-insert-every-2-elements-in-a-string
[7]: https://stackoverflow.com/questions/15254195/python-how-to-add-space-on-each-3-characters
[8]: https://stackoverflow.com/questions/10070434/how-do-i-insert-a-space-after-a-certain-amount-of-characters-in-a-string-using-p

**Comment by bbayles** [comment]
Good research, as always. I think this is a good generalization. I don't mind using `chunked` and `collapse` in the tool; these are supposed to be compose-able.

I think your implementation has an issue with `collapse`, though. Suppose you want to intersperse an iterable?
```python
>>> list(intersperse([1, 2], range(5)))
[0, [1, 2], 1, [1, 2], 2, [1, 2], 3, [1, 2], 4]
>>> list(new_intersperse([1, 2], range(5)))
[2, 0, 1, 2, 1, 1, 2, 2, 1, 2, 3, 1, 2, 4]
```

I'd accept a PR with this fixed (and tests for it).

**Comment by pylang** [comment]
Good point.   It will be about a week before I can access my personal computer to make a PR (first time btw, so bear with me as I figure it out).  I've implemented the fix and tests here should you wish to clear this issue sooner.

```python
# Add `n` kwarg to `interspearse`

from itertools import repeat, chain
from unittest import TestCase

from more_itertools import chunked, interleave
from nose.tools import eq_, assert_raises


def intersperse(e, iterable, n=1):
    """Intersperse object *e* between `n` items of *iterable*.
    
        >>> list(intersperse('x', 'ABCD'))
        ['A', 'x', 'B', 'x', 'C', 'x', 'D']
        >>> list(intersperse(None, [1, 2, 3]))
        [1, None, 2, None, 3]
        >>> list(intersperse(None, '01234', n=2))
        ['0', '1', None, '2', '3', None, '4']
        
    """
    it = chunked(iter(iterable), n)
    filler = repeat((e,))
    interleaved = interleave(filler, it)
    next(interleaved)
    return chain.from_iterable(interleaved)


class IntersperseTest(TestCase):
    """ Tests for intersperse() """

    def test_even(self):
        eq_(list(intersperse(None, '01')), ['0', None, '1'])

    def test_odd(self):
        eq_(list(intersperse(None, '012')), ['0', None, '1', None, '2'])

    def test_generator(self):
        iterable = (x for x in '012')
        eq_(list(intersperse(None, iterable)), ['0', None, '1', None, '2'])

    def test_n(self):
        eq_(list(intersperse(None, '012', n=2)), ['0', '1', None, '2'])
        eq_(list(intersperse(None, '01234', n=2)), ['0', '1', None, '2', '3', None, '4'])
        
    def test_elements(self):
        eq_(list(intersperse([1, 2], '012')), ['0', [1, 2], '1', [1, 2], '2'])
    
    def test_intersperse_not_iterable(self):
        assert_raises(TypeError, lambda: intersperse('x', 1))
```
