### ISSUE TITLE
No `StopIteration` in `peekable`

### ISSUE THREAD

**Issue by pylang** [erikrose/more-itertools#154]
I expect the following `peekable` code to raise a `StopIteration` error, but it runs without warning:

```python
iterable = "A B C".split()
p = mit.peekable(iterable)

while p:
    line = next(p)
    print(line, end=" ")
# A B C 
```

By comparison, most iterators and generators I've tried raise an error:

```python
iterable = "A B C".split()
p = iter(iterable)

while p:
    line = next(p)
    print(line, end=" ")
```
 Output
```
A B C 
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
<ipython-input-67-fe7c490ca45a> in <module>()
      3 
      4 while p:
----> 5     line = next(p)
      6     print(line, end=" ")

StopIteration:
```

Note, if replaced with `while True`, the `StopIteration` is raised as expected.   However, the sudden ending of the while loop in the first example seems like a bug as it is unclear why the loop ended.  I understand the `peek` method has an exception handler, although this method it is not directly called in the former example.  

Before investigating further, regarding the first example:

1. Is it intended behavior for `peekable` not to raise a `StopIteration`?
1. If so, what signals the `while` loop to end?

**Comment by bbayles** [comment]
Isn't this the result of `peekable()`-wrapped iterables having a `__bool__` method?

The `while` statement precedes an expression, which is evaluated repeatedly. If the expression is equivalent to `True` the loop body executes; otherwise it breaks.

Since your `peekable()`-wrapped iterable has a `__bool__` method that returns `True` when there are still items (this is [documented](https://more-itertools.readthedocs.io/en/latest/api.html#more_itertools.peekable)), then the loop body executes once for each item. On the next iteration there are no more items, so the `__bool__` method returns `False` and the loop body doesn't execute.

**Comment by pylang** [comment]
First, thanks for the fast response.  I believe I understand what's happening now thanks to your explanation.  I see now `peekable` has the [following `__bool__` method](https://github.com/erikrose/more-itertools/blob/master/more_itertools/more.py#L188-L193) defined:

```python
    ...
    def __bool__(self):
        try:
            self.peek()
        except StopIteration:
            return False
        return True
    ...
```

I assume this method defines the "truthiness" of an object, which is tested by the `while` statement.  This would explain both of my original questions.  Your explanation is sufficient to close this issue, as the truthiness of a `peekable` object is indeed documented.  

---

A few comments of non-actionable feedback - I suppose two things caught me off guard with `peekable`:
1. My initial instinct was to view it as a traditional generator, which when exhausted, raises `StopIteration`.  I realize more clearly this object is instead a specialized iterator.
1. I suspected the `peekable` object to always be `True` like most objects in Python (aside from standard ones like empty containers, `0`, `False` and `None`).   The idea of an object having dynamic truthiness takes getting used to, though permissible since `__bool__` allows this customization.

I'll have to look into the design decisions for `StopIteration` instead of `False` or `None`.  Thanks.
