### ISSUE TITLE
`lstrip` vs. `dropwhlie`

### ISSUE THREAD

**Issue by pylang** [erikrose/more-itertools#161]
I notice `more_itertools.lstrip` is similar to `itertools.dropwhile`:

```python
import itertools as it

import more_itertools as mit


iterable = [0, None, 1, 2, 0, 3, None, 0]
pred = lambda x: x in {None, 0}

list(mit.lstrip(iterable, pred))
# [1, 2, 0, 3, None, 0]

list(it.dropwhile(pred, iterable))
# [1, 2, 0, 3, None, 0]
```

I recall `lstrip` is a derivative of `strip`, but It may be worth noting in the docstring the similarity between `lstrip` and `dropwhile` (see #122).

**Comment by bbayles** [comment]
This is intentional; `lstrip` is only there as a companion to `rstrip`. The former is just another name for `dropwhile`, but the latter is more complicated.

**Comment by pylang** [comment]
Understood, as evident in the [source][1].  I'm suggesting a minor note in the docs for clarity.  Example: 

> Note that this a wrapper of ``dropwhile()`` from the `itertools` module.

  [0]: https://github.com/erikrose/more-itertools/blob/master/more_itertools/more.py#L1364
