### ISSUE TITLE
always_iterable treats dict as iterable

### ISSUE THREAD

**Issue by jaraco** [erikrose/more-itertools#164]
I'm finally getting around to reconciling `always_iterable` in [jaraco.itertools](/jaraco/jaraco.itertools), as contributed to this project in #37 and #108.

In September last year, I discovered that one would be unlikely to want to iterate over a dictionary (or other Mapping) when using `always_iterable`, so in [jaraco.itertools 2.0](http://jaracoitertools.readthedocs.io/en/latest/history.html#id2), Mappings were treated as non-iterable. The reasoning, as [found in the docs](http://jaracoitertools.readthedocs.io/en/latest/#jaraco.itertools.always_iterable), is that a dictionary is likely to be intended as a single object rather than a sequence of keys, but also that one can readily pass iter(dict) or dict.keys() if one does want the value to be treated as iterable.

In order for more_itertools.more.always_iterable to supplant jaraco.itertools.always_iterable, I'd like for more_itertools to adopt this behavior as well.

What do you think?

**Comment by bbayles** [comment]
My first intuition was that `always_iterable()` should let you loop over dict keys like normal, but I can see your point.

I [sort of wanted](https://github.com/erikrose/more-itertools/pull/108#discussion_r96780782) to take out the special handling of strings to make the default behavior super simple, but decided against it then.

I think PR #165 adds some flexibility such that we don't have to dictate which types are "not considered iterable." This is similar to what `collapse()` does, and can cover the `dict` case you mention.

I considered adding something for "don't override anything, just check `__iter__` if `base_type` is `None`" - any opinions about that? As-is you could do `base_type=type('Dummy', (), {})`.

**Comment by bbayles** [comment]
Sort of resolved in PR #165.
