### ISSUE TITLE
Iterable parameter in `windowed`

### ISSUE THREAD

**Issue by pylang** [erikrose/more-itertools#166]
I noticed the signature for `windowed` included `seq`, i.e. `windowed(seq, ...)`.   I consider sequences to be "sliceable iterables", so I think the correct name should be iterable instead, i.e. `windowed(iterable, ...)`.

From Python docs:

*sequence*

> An iterable which supports efficient **element access using integer indices via the __getitem__()** special method and defines a len() method that returns the length of the sequence. Some built-in sequence types are list, str, tuple, and unicode. Note that **dict also supports __getitem__() and __len__(), but is considered a mapping rather than a sequence** because the lookups use arbitrary immutable keys rather than integers.

*iterable*

> An object capable of returning its members one at a time. Examples of **iterables include all sequence types (such as list, str, and tuple) and some non-sequence types like dict**, file objects, and objects of any classes you define with an __iter__() method or with a __getitem__() method that implements Sequence semantics.

The reason I bring this up is because `sliced` requires a sequence (as well as certain Python builtins that exclude general iterables).  Since `windowed` can also be applied to non-sequences (e.g. dicts), `iterable` seems the appropriate variable name, consistent with other patterns in the source.

As far as I can tell, changing the name has no negative effect on the code as the iterable is made into an iterator and used no where else.

**Comment by bbayles** [comment]
Hmm, I think you're right about the terminology, but I'm not inclined to change the function. It would break calling with a keyword argument.

FWIW, all the summaries in the itertools documentation use `seq`:

![image](https://user-images.githubusercontent.com/1922815/31365751-b07f421a-ad32-11e7-9306-d75ba3298e03.png)

**Comment by pylang** [comment]
So it is.  Thanks.
