### ISSUE TITLE
seekable decorator

### ISSUE THREAD

**Issue by pylang** [erikrose/more-itertools#181]
Before `seekable` further diffuses into the wild, I wanted to ask if it is feasible to give `seekable`/`peekable`-like tools the option to decorate generator functions?  Example:

```python
from itertools import count


@seekable
def numbers():
    """Return an infinite iterator of numeric strings."""
    return (str(n) for n in count())

it = numbers()
next(it), next(it), next(it)
# ('0', '1', '2')
```

I am particularly interested in making normal generator functions "reusable" ([see last `Counter` example in the "Generators" section](https://pymbook.readthedocs.io/en/latest/igd.html#generators)).  The `seekable` class seems it may able to do this simply.  This is just a rough idea, so I am not partial to the example mentioned here.

**Comment by bbayles** [comment]
Ah, this is interesting. The normal decorator pattern does work with generator functions:

<details><summary>Function decorator</summary>

```python
>>> from functools import wraps
... from more_itertools import seekable
... 
... def seekable_generator(f):
...     @wraps(f)
...     def wrapper(*args, **kwargs):
...         return seekable(f(*args, **kwargs))
... 
...     return wrapper
... 
... @seekable_generator
... def yielder(n):
...     for i in range(n):
...         yield i
... 
... g = yielder(10)
... print(list(g))
... g.seek(0)
... print(list(g))
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

</details>

---

This is really neat, but I'm not sure if that really buys much - why not just do the usual thing (wrap the return value of the generator function), as below?


<details><summary>Normal usage</summary>

```python
... g = seekable(yielder(10))
... print(list(g))
... g.seek(0)
... print(list(g))
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

</details>

---

Assuming `peekable()` or `seekable()` are useful as decorators, does it make sense to make separate functions for them as decorators? That would involve making new names like `seekable_generator()` above.

An alternative would be to overload the functionality of `seekable()` to detect when it's being used as a decorator:

<details><summary>Class-based decorator</summary>

```python
... class seekable(object):
...     def __init__(self, x):
...         if callable(x):
...             self._func = x
...         else:
...             self._source = iter(x)
...         self._cache = []
...         self._index = None
...     
...     def __call__(self, *args, **kwargs):
...         self._source = iter(self._func(*args, **kwargs))
...         return self
...
...     # etc. etc. etc.
... 
... @seekable
... def yielder(n):
...     for i in range(n):
...         yield i
... 
... g = yielder(10)
... print(list(g))
... g.seek(0)
... print(list(g))
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

</details>

---

This is sort of a hack, though, and I'm not sure if I like it.

Thoughts?

**Comment by pylang** [comment]
Applying the decorator pattern solves my question as a reasonable workaround. 

I had in mind more of your last example, where the `seekable` class has the decorator option baked in, i.e. use `seekable` either as a decorator or a regular function wrapper.

I can't say you get much out of it other than saving some typing and possibly dryer code. For example, in refactoring code that calls the same helper generator, it seems easier to add/remove the  `@seekable` decorator to the base generator than to add/remove new lines for each instantiation.  

```python
g1 = seekable(yielder(9))
g2 = seekable(yielder(10))
g3 = seekable(yielder(11))
...
```

Compared to a decorator

```python
@seekable
def yielder(n):
    ...

g1 = yielder(9)
g2 = yielder(10)
g3 = yielder(11)
```

I don't feel there is ton of momentum for making a big change to the source at the moment.   However, the idea might be worth documenting, hence the post.  I suppose for now, your first snippet of the decorator will suffice.  Many thanks.

**Comment by bbayles** [comment]
I think I'm finished with PR #183; I'll leave it open for comment.

---

To push this idea to absurd limits, consider this decorator decorator factory (I ran out of variable names):

```python
from functools import wraps

def factory(module_func, iterable_index=0):
    def meta(*module_args, **module_kwargs):
        def outer_wrapper(user_func):
            @wraps(user_func)
            def inner_wrapper(*user_args, **user_kwargs):
                user_result = user_func(*user_args, **user_kwargs)
                module_args_ = list(module_args)
                module_args_.insert(iterable_index, user_result)
                return module_func(*module_args_, **module_kwargs)
            return inner_wrapper
        return outer_wrapper
    return meta
```

And these decorators:

```python
from more_itertools import chunked, grouper, windowed

chunk_maker = factory(chunked)
window_maker = factory(windowed)
grouper_maker = factory(grouper, 1)

@chunk_maker(3)
def c_yielder(n):
    return iter(range(n))


@window_maker(3, step=4)
def w_yielder(n):
    return iter(range(n))


@grouper_maker(3)
def g_yielder(n):
    return iter(range(n))
```

The results are as you might expect:

```python
>>> print(list(c_yielder(10)))
... print(list(w_yielder(10)))
... print(list(g_yielder(10)))
[[0, 1, 2], [3, 4, 5], [6, 7, 8], [9]]
[(0, 1, 2), (4, 5, 6), (8, 9, None)]
[(0, 1, 2), (3, 4, 5), (6, 7, 8), (9, None, None)]
```

The cute/terrible thing is adapting the various function signatures with the `iterable_index` - it lets `chunked(iterable, n)` and `grouper(n, iterable)` both work.

I think this is a bit too "yo dawg, I heard you like decorators, so I put a decorator on your decorator so you can decorate while you decorate" for comfort, but I had fun puzzling out the closure mechanics.

**Comment by pylang** [comment]
I'm amazed what you've been able to do and appreciate your awesome work.  Thank you.

As for the decorator factory, first impressions:  

-  I ... kinda like it :+1:  On one hand it feels seems like an elegant abstraction for a clean way to reuse tools.  On the other hand it has a "Release the Kraken!" feel that gives me pause, as  I can't foresee the consequences, provided such an approach works on all tools.
- If this was to potentially become a thing, I think I'd introduce it provisionally,  written somewhere that it's aimed for advanced intermediate users for now.   Decorators could scare new users, unaccustomed to the present instantiation/iter-like conventions.  But I think it is nice to have a new "interface" for using the tools in this library.

And now ... I'm off to try this idea out on more tools.  ))

**Comment by bbayles** [comment]
I wrote [this post](https://t.co/Ui8Ps8QUhm) on the topic, explaining the decorator factory factory.

**Comment by erikrose** [comment]
"This starts out innocently enough." is a great hook. :-)

**Comment by pylang** [comment]
+1 for "double dec-er"

**Comment by pylang** [comment]
Along the lines of exploration, here is an abstraction that obviates the `iterable_index` parameter in a [prior example][2], e.g. the user can write `factory(grouper)` instead of `factory(grouper, 1)`.

Included is a sample implementation with tests.

<details>
 <summary>Imports</summary>

```python
import inspect
from typing import Iterable
from itertools import dropwhile, zip_longest
from functools import wraps, partial

import nose.tools as nt
import more_itertools as mit
```
</details>


<details>
 <summary>Modifications</summary>

```python
def locate_iterable(func):
    """Return the position of an iterable argument (requires Python 3.5+)"""
    sig = inspect.signature(func)
    sig_ = [param.annotation for param in sig.parameters.values()]
    
    pred = lambda x: x[1] == Iterable
    first_iterable = mit.first_true(enumerate(sig_), default=None, pred=pred)
    if first_iterable is None:
        raise TypeError("Factory requires an iterable or sequence.")
    return first_iterable[0]


def factory(module_func):
    def meta(*module_args, **module_kwargs):
        def outer_wrapper(user_func):
            @wraps(user_func)
            def inner_wrapper(*user_args, **user_kwargs):
                user_result = user_func(*user_args, **user_kwargs)
                module_args_ = list(module_args)
                iterable_index = locate_iterable(module_func)   # edit
                module_args_.insert(iterable_index, user_result)
                return module_func(*module_args_, **module_kwargs)
            return inner_wrapper
        return outer_wrapper
    return meta
```
</details>

Now the user does not have to manually specify where the iterable is located.  Rather, the location of the first iterable type in the module-level function is determined via type annotations.  This simplification should lead to more intuitive wrapping of tools:


Demo

```python
#grouper_maker = factory(grouper, 1)                        # old
grouper_maker = factory(grouper)                           # new

@grouper_maker(3)
def g_yielder(n):
    return iter(range(n))

print(list(g_yielder(10)))
[(0, 1, 2), (3, 4, 5), (6, 7, 8), (9, None, None)]
```

Using the new type annotations would of course require annotating source code, example:

```python
# Annotated Tools
def chunked(iterable:Iterable, n:int):                     # annotations
    return iter(partial(mit.take, n, iter(iterable)), [])


def grouper(n:int, iterable:Iterable, fillvalue=None):     # annotations 
    args = [iter(iterable)] * n
    return zip_longest(fillvalue=fillvalue, *args)
```

<details>
 <summary>Tests</summary>

```python
class TestLocateIterable:
    # Helper functions with arbitrary signatures
    def foo(a, *, b:int, **kwargs):
        pass

    def bar(a, b, iterable:Iterable, *, c:int, **kwargs):
        pass


    @nt.raises(TypeError)
    def test_error(self):
        """Verify an error is raised if no iterables parameters are found."""
        cls = TestLocateIterable
        print(locate_iterable(cls.foo))
        
    def test_index(self):
        """Verify the index of the first iterable parameter."""
        cls = TestLocateIterable
        nt.eq_(locate_iterable(cls.bar), 2)
        

test = TestLocateIterable()
test.test_error()
test.test_index()


class TestIterables:

    # Annotated functions
    chunk_maker = factory(chunked)
    grouper_maker = factory(grouper)
    
    @staticmethod
    @chunk_maker(3)
    def c_yielder(n):
        return iter(range(n))

    @staticmethod
    @grouper_maker(3)
    def g_yielder(n):
        return iter(range(n))

    
    def test_iterables(self):
        cls = TestIterables
        nt.eq_(list(cls.c_yielder(10)), [[0, 1, 2], [3, 4, 5], [6, 7, 8], [9]])
        
    def test_reversed_signature(self):
        cls = TestIterables
        nt.eq_(list(cls.g_yielder(10)), [(0, 1, 2), (3, 4, 5), (6, 7, 8), (9, None, None)])


test = TestIterables()
test.test_iterables()
test.test_reversed_signature()

```
</details>


Caveats

- The modified `factory` decorator assumes the first iterable in `module_func` is "correct", which may fail for signatures with unconventional naming.
- [Type hints][0] is only compatible with Python 3.5+ and 2.7, limiting backwards compatibility
- Inspecting function signatures in `locate_iterable` is [compatible with Python 3.3+][1]
- This option raises the chore of annotating source code


Conclusion

The option for further abstracting the `factory` proposal is possible for later versions of Python.  Perhaps someday, this endeavor may be revisited followed by a motivation to annotate the source.


  [0]: https://stackoverflow.com/questions/32557920/what-are-type-hints-in-python-3-5
  [1]: https://docs.python.org/3/library/inspect.html#introspecting-callables-with-the-signature-object
  [2]: https://github.com/erikrose/more-itertools/issues/181#issuecomment-350423213

**Comment by bbayles** [comment]
Yeah, this is a neat line of research. I fiddled with signature inspection originally, but couldn't make anything clean. I was disappointed to find out `collections.abc.Iterable` doesn't do what I want:

> The only reliable way to determine whether an object is iterable is to call iter(obj).

If anyone reading wants to try it out, I *might* accept a PR that adds type checking with `mypy` (with the 2.7 compatible hints), though don't spend the time doing everything.
