### ISSUE TITLE
map/reduce recipe

### ISSUE THREAD

**Issue by pylang** [erikrose/more-itertools#195]
Would this [`map_reduce` recipe][0] by R. Hettinger be of interest?  Here is an example from the docstring:

    >>> def even_odd(elem):                     # sample mapper
    ...     if 10 <= elem <= 20:                # skip elems outside the range
    ...         key = elem % 2                  # group into evens and odds
    ...         return key, elem

    >>> map_reduce(range(30), even_odd)         # show group members
    {0: [10, 12, 14, 16, 18, 20], 1: [11, 13, 15, 17, 19]}

    >>> map_reduce(range(30), even_odd, sum)    # sum each group
    {0: 90, 1: 75}

  [0]: https://code.activestate.com/recipes/577676-dirt-simple-mapreduce/?in=user-178123

**Comment by bbayles** [comment]
Hmm, yes. I like it - it's actually very similar to the `defaultdict(list)-maker` I played with in PR #188. The "reduce" part is an optional part added onto the end.

A simpler version would use `defaultdict(list`) and leave out the "skip where the `mapper` returns `None`" (that can be implemented in the reducer). This feels like a better inclusion than what I was groping toward before, so if you want to message Raymond H. and ask for his blessing, I'm good with it? (he previously sanctioned [this one](https://twitter.com/bbayles/status/865353484383776768)).

I'd be interested also if someone wants to explore something like this for `bucket` - at each stage it could yield the "reduction." Something like `bucket` + `accumulate`.

---

```python
def map_reduce(iterable, map_func, reduce_func=None):
    ret = defaultdict(list)
    for item in iterable:
        ret[mapper(item)].append(item)

    if reduce_func is not None:
        for k, v in ret.items():
            ret[k] = reduce_func(v)
    
    return ret

```

**Comment by rhettinger** [comment]
Yes, go ahead.

**Comment by pylang** [comment]
Many thanks @rhettinger.

@bbayles I like using `defaultdict`.  It's  clean, but I believe removing `if r is not None:`  will cause  `map_func`  to behave more like a `key_func`.   Any transformations from the mapping function would be added as a key rather than split between a key, value pair.

```python
def even_odd_transform(elem):
    key = elem % 2
    return key, 10*elem


def map_reduce_proposed(iterable, map_func, reduce_func=None):
    ret = ct.defaultdict(list)
    for item in iterable:
        ret[map_func(item)].append(item)

    if reduce_func is not None:
        for k, v in ret.items():
            ret[k] = reduce_func(v)
    
    return ret

print(map_reduce(range(5), even_odd_transform))
# {0: [0, 20, 40], 1: [10, 30]}

print(map_reduce_proposed(range(5), even_odd_transform))
# defaultdict(<class 'list'>, {(1, 10): [1], (0, 40): [4], (0, 0): [0], (1, 30): [3], (0, 20): [2]})
```

Note the key and transformed value is added as keys to the `defaultdict`. I assume this is an undesired result.  You could still use the defaultdict of course and get the same result:

```python
def map_reduce_revised(iterable, map_func, reduce_func=None):
    ret = ct.defaultdict(list)
    for item in iterable:
        r = map_func(item)
        if r is not None:
            key, value = r
            ret[key].append(value)
...

print(map_reduce_revised(range(5), even_odd_transform))
# defaultdict(<class 'list'>, {0: [0, 20, 40], 1: [10, 30]})
```

**Comment by bbayles** [comment]
Notice the examples in the original recipe are easily replicated:

```python
keyfunc = lambda p: (p.gender, p.age // 10)
valuefunc = lambda p: p.height

pprint(persons)  # upgrouped dataset
pprint(map_reduce(persons, keyfunc)) # grouped people
pprint(map_reduce(persons, keyfunc, valuefunc))  # grouped heights
pprint(map_reduce(persons, keyfunc, valuefunc, len))  # size of each group
pprint(map_reduce(persons, keyfunc, valuefunc, describe))  # describe each group

```

**Comment by bbayles** [comment]
I'll merge the PR sooner or later; many thanks to all involved.

Something to think about - below is one of my favorite patterns:

---

<details> <summary>Code sample</summary>

```python
from collections import defaultdict
from random import randrange


class Aggregator:
    def __init__(self):
        self.low = float('inf')
        self.high = float('-inf')
        self.count = 0
        self.total = 0
    
    def update(self, item):
        self.low = min(item, self.low)
        self.high = max(item, self.high)
        self.count += 1
        self.total += item
    
    def __repr__(self):
        return str(self.__dict__)


iterable = [randrange(-1000, 1000) for n in range(1000)]

D = defaultdict(Aggregator)
for item in iterable:
    key = abs(item) // 100
    value = item * item
    D[key].update(value)
```

</details>

---

You can see the last loop is very similar to the  `map_reduce` function we're discussing here, but instead of "gather everything up into memory and then reduce at the end," we're continually reducing.

An example of this in action in the real world is [here](https://github.com/obsrvbl/flowlogs-reader/blob/63977dc787f289f8f62582a079efc67701cd9c8b/flowlogs_reader/aggregation.py) - taking a network traffic log and computing stats on millions of lines. [Here](https://stackoverflow.com/a/2937417/353839) is another example from a different domain (the source was a big historical database).

I *think* it's hard to save any work with a library function that does this task, because the heavy lifting is in the `Aggregator` class's `update` function. If someone has time to noodle around and figure out something elegant, I'd be interested in including it.

**Comment by pylang** [comment]
Here's a first pass at noodling with @bbayles' ["lazy reducer" and his `Aggregator` class](https://github.com/erikrose/more-itertools/issues/195#issuecomment-365134822).

Summary: `map_reduce` + custom reducing default_factory/method

---

<details>
<summary>Setup</summary>

```python
import random
import collections as ct



class Aggregator:
    def __init__(self):
        self.low = float('inf')
        self.high = float('-inf')
        self.count = 0
        self.total = 0
    
    def update(self, item):
        self.low = min(item, self.low)
        self.high = max(item, self.high)
        self.count += 1
        self.total += item
    
    def __repr__(self):
        return str(self.__dict__)
```
    
</details>

---

```python
def reaggregate(iterable, keyfunc, valuefunc, reducefunc=None, reducefactory=list):
    ret = ct.defaultdict(reducefactory)
    for item in iterable:
        key = keyfunc(item)
        value = valuefunc(item)
            
        if (reducefunc is not None) and (reducefactory is not list):
            reducemeth = reducefunc
            getattr(ret[key], reducemeth)(value)   # defer
        else:
            ret[key].append(value)                 # gather
            
    if (reducefunc is not None) and (reducefactory is list):        
        for key, value_list in ret.items():
            ret[key] = reducefunc(value_list)

    ret.default_factory = None
    
    return ret

```

---

<details>
<summary>Demo</summary>

It's nice to pass in a custom default factory (e.g. `Aggregator`) to the internal `defaultdict`.

```python
kfunc = lambda x: abs(x) // 100
vfunc = lambda y: y * y
rmeth = "update"

iterable = [random.randrange(-1000, 1000) for n in range(1000)]
reaggregate(iterable, kfunc, vfunc, reducefunc=rmeth, reducefactory=Aggregator)
```

The reduction was deferred to the `Aggreator`.   In this case, a reducing method was specified.

Of course you can fallback to gathering and/or applying a reducing function later.

```python
kfunc = lambda x: abs(x) // 100
vfunc = lambda y: y * y
rfunc = sum

iterable = [random.randrange(-1000, 1000) for n in range(20)]
reaggregate(iterable, kfunc, vfunc, reducefunc=rfunc)
```

</details>



---

I am not partial to the names or this particular implementation.

**Comment by bbayles** [comment]
While thinking about @pylang's code I had the thought that since we have to do the `Aggregator`-type classes anyway, why not just augment them with the code needed to do the map/reduce stuff?

---

<details> <summary>AggregatorBase</summary>

```python
from abc import ABCMeta, abstractmethod
from six import add_metaclass


@add_metaclass(ABCMeta)
class AggregatorBase(object):
    @abstractmethod
    def __init__(self):
        pass

    @abstractmethod
    def update(self, item):
        pass

    @classmethod
    def aggregate(cls, iterable, keyfunc, valuefunc=None):
        valuefunc = (lambda x: x) if (valuefunc is None) else valuefunc

        ret = defaultdict(cls)
        for item in iterable:
            key = keyfunc(item)
            value = valuefunc(item)
            ret[key].update(value)

        return ret
```

</details>

---

<details><summary>Custom aggregators</summary>

```python
class MinMax(AggregatorBase):
    def __init__(self):
        self.low = float('inf')
        self.high = float('-inf')
    
    def update(self, item):
        self.low = min(item, self.low)
        self.high = max(item, self.high)
    
    def __repr__(self):  # This is just here to make the demo easier
        return 'MinMax<{}, {}>'.format(self.low, self.high)


class Mean(AggregatorBase):
    def __init__(self):
        self._n = 0
        self._total = 0
    
    def update(self, item):
        self._n += 1
        self._total = item    

    @property
    def mean(self):
        return (self._total / self._n) if self._total else 0
    
    def __repr__(self):  # This is just here to make the demo easier
        return 'Mean<{:.02f}>'.format(self.mean)
```

</details>

---

<details><summary>Usage</summary>

```python
from random import randrange

iterable = [randrange(-1000, 1000) for n in range(1000)]
keyfunc = lambda x: abs(x) // 100
valuefunc = lambda x: x * x

category_min_max = MinMax.aggregate(iterable, keyfunc=keyfunc, valuefunc=valuefunc)
category_mean = Mean.aggregate(iterable, keyfunc=keyfunc, valuefunc=valuefunc)
```

```python
>>> category_min_max
defaultdict(<class '__main__.MinMax'>,
            {0: MinMax<0, 9801>,
             1: MinMax<10000, 39601>,
             2: MinMax<40000, 89401>,
             3: MinMax<91204, 159201>,
             4: MinMax<160000, 249001>,
             5: MinMax<251001, 358801>,
             6: MinMax<360000, 485809>,
             7: MinMax<490000, 636804>,
             8: MinMax<644809, 808201>,
             9: MinMax<811801, 998001>,
             10: MinMax<1000000, 1000000>})

>>> category_mean
defaultdict(<class '__main__.Mean'>,
            {0: Mean<17.13>,
             1: Mean<271.02>,
             2: Mean<666.12>,
             3: Mean<1863.58>,
             4: Mean<2255.53>,
             5: Mean<3151.74>,
             6: Mean<4705.96>,
             7: Mean<5971.25>,
             8: Mean<7300.82>,
             9: Mean<10076.51>,
             10: Mean<1000000.00>})
```

</details>

---

Here we have `AggreagatorBase`, which automates the `defaultdict` stuff (i.e. that which is repetitive). To use it, you subclass it and provide the `__init__` method (which sets up the things you're going to keep track of) and the `__update__` method (which handles the reduction).

This seems like a fruitful line of inquiry - different aggregator classes could do keep track of things like "on-line" means, [running medians](https://rhettinger.wordpress.com/tag/running-median/), the last N items, etc. etc. etc.
