### ISSUE TITLE
unexpected behavior with `groupby_transform`

### ISSUE THREAD

**Issue by meereeum** [erikrose/more-itertools#203]
```.py
grouper = lambda l: [(k, list(g)) for k,g in groupby_transform(l, lambda tup: tup[1], lambda tup: tup[0])]

> l = [(5,4), (3,4), (5,6)]
> grouper(l)

[(4, [5, 3]), (6, [5])]

> l = [(3,4), (5,4), (5,6)]
> grouper(l)

[(4, [3, 5]), (6, [5])]

> l = [(3,4), (5,6), (5,4)]
> grouper(l)

[(4, [3]), (6, [5]), (4, [5])]
```

unless i'm misunderstanding something fundamental about intended behavior, last function should return the same as first two..

**Comment by pylang** [comment]
This is native behavior of `itertools.groupby`, and sorting is discussed in the [docs][1]:

> Generally, the iterable needs to already be sorted on the same key function.

Native `groupby` is intrinsically tricky for new users and has been [discussed elsewhere][2].  As it is already documented, there is no need to rehash these insights in detail.   Maybe a link to a reference would suffice. 

  [1]: https://docs.python.org/3/library/itertools.html#itertools.groupby
  [2]: https://stackoverflow.com/questions/773/how-do-i-use-pythons-itertools-groupby

**Comment by bbayles** [comment]
Ah, I think I will add a note to the docs.

**Comment by bbayles** [comment]
As I look at this, I remember picking the examples in the docs to illustrate this.

```python
        >>> iterable = 'AaaABbBCcA'
        >>> keyfunc = lambda x: x.upper()
        >>> valuefunc = lambda x: x.lower()
        >>> grouper = groupby_transform(iterable, keyfunc, valuefunc)
        >>> [(k, ''.join(g)) for k, g in grouper]
        [('A', 'aaaa'), ('B', 'bbb'), ('C', 'cc'), ('A', 'a')]
```

**Comment by meereeum** [comment]
> Generally, the iterable needs to already be sorted on the same key function.

that is strangely phrased (re: "generally" - implies exceptions ?). but that is independent of this project!

**Comment by bbayles** [comment]
The exception would be if you don't mind having duplicate groups. I've added a note about this in PR #204. I made the mistake of not sorting something passed to `groupby` at work the other day.

**Comment by bbayles** [comment]
Many thanks for the suggestion.
