### ISSUE TITLE
Pluck?

### ISSUE THREAD

**Issue by jdunck** [erikrose/more-itertools#223]
Would a thing like underscore.js's `pluck` be welcomed?

https://underscorejs.org/#pluck

**Comment by pylang** [comment]
I don't speak for whether it's welcomed or not, but this kind of filtering can be done pretty easily in Python:

```python
iterable = [{"name": "moe", "age": 40}, {"name": "larry", "age": 50}, {"name": "curly", "age": 60}]

[v for d in iterable for k, v in d.items() if k == "name"]
# ['moe', 'larry', 'curly']
```

Maybe I'm missing something.  Did you have another use case in mind?

**Comment by bbayles** [comment]
I think adapting useful things from other languages is potentially a good idea, but I do agree that `pluck` is better solved with existing tools.

```python
>>> from operator import itemgetter
... 
... iterable = ({"name": "moe", "age": 40}, {"name": "larry", "age": 50}, {"name": "curly", "age": 60})
... 
... list(map(itemgetter('name'), iterable))
0: ['moe', 'larry', 'curly']
```

Or even better:
```python
>>> iterable = ({"name": "moe", "age": 40}, {"name": "larry", "age": 50}, {"name": "curly", "age": 60})
... 
... [d['name'] for d in iterable]
1: ['moe', 'larry', 'curly']
```

**Comment by jdunck** [comment]
Yep, I know about dictionary comprehensions. :)

FWIW, I'm already using more_itertools, and I think `pluck` is an idiomatic helper.  Here's a snip of the use I have:

```
    sorted_expected = [
        sorted(_pluck(r["requests"], "url", "method"), key=lambda r: r["url"])
        for r in expected_bodies
    ]
```
where `expected_bodies` is a list of dictionaries, each containing `"requests"`, which a list of further dictionaries, each containing a bunch of properties I don't care about, except for "url" and "method".

But I agree that where to draw the line on a package like this is an editorial decision, and this may not be hard enough to warrant inclusion in the library.  I'll close the ticket. :)

**Comment by bbayles** [comment]
I do like the idea of "itemgetter, but for multiple things."

What do you think of this?

```python
>>> def getitems(d, *keys):
...     return tuple(d[k] for k in keys)
... 
... 
... all_dicts = [
...     {'request': 'a', 'url': 'b', 'other': 'c'},
...     {'request': 'd', 'url': 'e', 'other': 'f'},
...     {'request': 'g', 'url': 'h', 'other': 'i'},
... ]
... 
... [getitems(d, 'request', 'url') for d in all_dicts]
0: [('a', 'b'), ('d', 'e'), ('g', 'h')]
```

**Comment by erikrose** [comment]
I could go either way on this. I'd probably spell it like this, in pluck's absence:

```python
[itemgetter('url', 'method')(body) for body in expected_bodies]
```
vs
```python
pluck(expected_bodies, 'url', 'method')
```

I may have just argued myself into `pluck` iff it's a common enough need. Nice, to see you, @jdunck!

**Comment by erikrose** [comment]
Btw, itemgetter does do multiple things!

**Comment by bbayles** [comment]
Wow, it does! My mind is blown.

**Comment by jdunck** [comment]
Multi `itemgetter` does what I want, thanks for the lesson.  And hello, @erikrose :)

**Comment by pylang** [comment]
The development of this discussion points to a possible abstraction of this proposal.  Particularly, it would be interesting if such a tool was able to:

1. yield values for a given key
1. handle multiple attributes/keys
1. traverse nested containers

The first is the OP.  The second has been discussed a bit already (via `operator.itemgetter()`).  The third can be tricky, but it is a ubiquitous problem, so a tool that handles nested containers might have a big impact. 

Examples
----------
Signature: `pluck(iterable, *keys) -> defaultdict`

<details>
<summary>
Given some nested items
</summary>

```python
nested_dicts_1 = [
    {
        "animal": {
            "type": "rabbit"
        },
    },
    {
        "animal": {},
    },
]

nested_dicts_2 = [
    {
        "title" : "grandpa",
        "child": {
            "title" : "dad",
            "child": {
                "title": "son",
            },
        },
    },
]
```
</details>

<details>
<summary>
Demo of traversing (3)
</summary>

```python
>>> list(pluck(nested_dicts_1, "animal"))
defaultdict(list, {'animal': [{'type': 'rabbit'},  {}]})

>>> list(pluck(nested_dicts_1, "type"))
defaultdict(list, {'type': ['rabbit']})

>>> list(pluck(nested_dicts_2, "title"))
defaultdict(list, {'title': ['grandpa', 'dad', 'son']})
```
</details>

<details>
<summary>
Demo for multiple keys (2)
</summary>

```python
>>> pluck(nested_dicts_1, "animal", "type")
defaultdict(list, {
    'animal': [{'type': 'rabbit'},  {}],
    'type': ['rabbit'],
})
```
</details>

---
This idea is not fully fleshed out.  There are other nested container types and configurations to consider.  Any thoughts on the general idea of an abstracted `pluck` with the listed features?


References
------------

- Blog on [Handling complex nested dicts in Python](https://www.haykranen.nl/2016/02/13/handling-complex-nested-dicts-in-python/)
- SO post on [Loop through all nested dictionary values?](https://stackoverflow.com/questions/10756427/loop-through-all-nested-dictionary-values)
- Python-ideas thread on ["coalescing" attributes](https://mail.python.org/pipermail/python-ideas/2018-July/052288.html)

**Comment by jdunck** [comment]
Generally, nested key names aren't unique, so I'd prefer something like jsonpath to specify keys.  But I've definitely written a thing not entirely unlike this more than a couple times.

**Comment by erikrose** [comment]
I might have found something like that (complete with jsonpaths or whatever) useful when I was working on https://github.com/keleshev/schema, a general data-structure-validation lib.

**Comment by bbayles** [comment]
[jmespath](http://jmespath.org/) is my weapon of choice.

**Comment by pylang** [comment]
Thanks guys.  I learned something new about the JSON querying.   In the meantime, I prototyped my earlier idea.  It depends on [nvie's `traverse()` function](https://gist.github.com/nvie/f304caf3b4f1ca4c3884).  I guess i'll leave it here for anyone interested in the future. 

<details>
<summary>
Dependency
</summary>

```python
def traverse(obj, path=None, callback=None):
    """
    Traverse an arbitrary Python object structure (limited to JSON data
    types), calling a callback function for every element in the structure,
    and inserting the return value of the callback as the new value.
    """
    if path is None:
        path = []

    if isinstance(obj, dict):
        value = {k: traverse(v, path + [k], callback)
                 for k, v in obj.items()}
    elif isinstance(obj, list):
        value = [traverse(elem, path + [[]], callback)
                 for elem in obj]
    else:
        value = obj

    if callback is None:
        return value
    else:
        return callback(path, value)
```
</details>

---
**Code**

```python
def pluck(obj, *keys):
    """Return a defaultdict of targeted keys."""
    # Init defaultdict
    keys = set(keys)
    _d = {k : [] for k in keys}
    result = ct.defaultdict(list, **_d)
    
    def observe(path, value):
        nonlocal result

        # Pop the last part of the path; make None if []
        try:
            k = path[:].pop()
        except IndexError:
            suffix = set()
        else:
            suffix = set()
            k = None if not k else k
            suffix.add(k)

        #print(path, suffix, keys)
        if keys.intersection(suffix):
            result[k].append(value)
            return value
        return value

    traverse(obj, callback=observe)
    
    return result
```

**Demo**

```python
>>> pluck(nested_dicts_1, "animal")
# defaultdict(list, {'animal': [{'type': 'rabbit'},  {}]})

>>> pluck(nested_dicts_1, "type")
# defaultdict(list, {'type': ['rabbit']})

>>> pluck(nested_dicts_2, "title")
# defaultdict(list, {'title': ['grandpa', 'dad', 'son']})

>>> pluck(nested_dicts_1, "animal", "type")
# defaultdict(list, {'type': ['rabbit'], 'animal': [{'type': 'rabbit'}, {}]})
```


It's rough, a bit hacky, but I'm kind of shocked it worked with the example and [nvie's sample json](https://gist.github.com/nvie/f304caf3b4f1ca4c3884#file-specific-py) too.  

The idea is simple:
- `traverse()` iterates and returns each part of the given object
- `pluck` calls `traverse()` and scans if the keys are observed
- observations are added to a `defaultdict` and return

There's some details on how "paths" to the key work in his [blog post](https://nvie.com/posts/modifying-deeply-nested-structures/).

Nice discussion.  Cheers!
