### ISSUE TITLE
Subsequences

### ISSUE THREAD

**Issue by pylang** [erikrose/more-itertools#227]
A [subsequence](https://en.wikipedia.org/wiki/Subsequence) is a subset of a sequence, ordered but not necessarily consecutive/contiguous.

They show up in mathematics, computer science, linguistics, and natural sciences.   There is interest in them:

- [Longest Increasing Subsequence](https://stackoverflow.com/questions/2631726/how-to-determine-the-longest-increasing-subsequence-using-dynamic-programming) and [here](https://stackoverflow.com/questions/3992697/longest-increasing-subsequence)
- [Longest Repeated Substring](https://stackoverflow.com/questions/11090289/find-longest-repetitive-sequence-in-a-string) and [here](https://codereview.stackexchange.com/questions/63329/finding-the-largest-repeating-substring)
- [Longest Palindromic Subsequence](https://codereview.stackexchange.com/questions/161775/length-of-longest-palindrome-subsequence)

They are part of classic algorithmic problems:

- [Longest Common Subsequence Problem](https://en.wikipedia.org/wiki/Longest_common_subsequence_problem)
- [Longest Common Substring Problem](https://en.wikipedia.org/wiki/Longest_common_substring_problem)

Q: What are thoughts on adding a tool that simply collects subsequences?

# Examples

Haskell offers a [`subsequences` tool](https://hackage.haskell.org/package/base-4.11.1.0/docs/Data-List.html#v:subsequences):

**Haskell**

```python
>>> subsequences "abc"
["","a","b","ab","c","ac","bc","abc"]
```

It turns out our [`powerset` recipe](https://more-itertools.readthedocs.io/en/stable/_modules/more_itertools/recipes.html#powerset) is akin to this tool:

**Python**

```python
 >>> list(powerset([1,2,3]))
 [(), (1,), (2,), (3,), (1, 2), (1, 3), (2, 3), (1, 2, 3)]
```

**Limitations**

These tools only pertain to generic subsequences alone with limited options. 

- While iterating, the items cannot be altered (no `pred`)
- On "longest xyz problems," the longest items are at the end of the iterator (no `reverse`)
- Some problems require a "substring" of contiguous elements, i.e. `"ac"` and `(1, 3)` are invalid

# Implementation

**Proposal**

A possible implementation to handle the latter limitations might be the following:

```python
def subsequences(iterable, pred=None, reverse=False, contiguous=False):
    """Return windows of all subsequences sized from `len(iterable)` to 1.

    Examples
    --------
    >>> list(subsequences("abc"))
    [('a',), ('b',), ('c',), ('a', 'b'), ('a', 'c'), ('b', 'c'), ('a', 'b', 'c')]
    >>> list(subsequences("abc", contiguous=True))
    [('a',), ('b',), ('c',), ('a', 'b'), ('b', 'c'), ('a', 'b', 'c')]
    >>> list(subsequences("abc", reverse=True))
    [('a', 'b', 'c'), ('a', 'b'), ('b', 'c'), ('a',), ('b',), ('c',)]
    
    References
    ----------
    .. [1]: Haskell. `subsequences`. 
       https://hackage.haskell.org/package/base-4.11.1.0/docs/Data-List.html#v:subsequences
    .. [2]: Subsequence.  Wikipedia. https://en.wikipedia.org/wiki/Subsequence
    
    """
    iterable = tuple(iterable)
    range_ = range(len(iterable)+1)
    
    if pred is None:
        pred = lambda x: x

    if reverse: 
        range_ = reversed(range_)

    if contiguous:
        yield from (w for n in range_ for w in mit.windowed(iterable, n) if pred(w))
    else:
        # Roughly equivalent to `mit.powerset(iterable)` if `reverse=False`
        yield from (x for sub in (it.combinations(iterable, r) for r in range_) for x in sub if pred(x))

```
 
**Behaviors**

- Naturally, it behaves like a modified powerset, yielding a traditional subsequence (including both non-contiguous and contiguous elements).
- [Substrings](https://en.wikipedia.org/wiki/Substring) are possible by setting `contiguous=True`.
- Unlike a strict [powerset](https://en.wikipedia.org/wiki/Power_set), the null set is dropped.  It may be argued on how to keep it.

Note, I am not particular to any of these names or to this specific implementation.

**Comment by bbayles** [comment]
Many thanks for the writeup.

I'm generally disinclined to add `subsequences()`, given that `powerset()` and `windowed()` are at hand. This does make me think of some related things, however. See if any of these catch your imagination.

---

I've always liked the "integer partitions" algorithms [here](http://jeromekelleher.net/category/combinatorics.html), and have thought about adding it to `more-itertools`. If I could come up with some way to apply it to other interesting data types I would do it.

For example, `consecutive_groups()` was originally for numbers, but can be made to work with anything that maps to numbers - string indices, IP addresses, etc. ([example](https://github.com/erikrose/more-itertools/pull/169/files#diff-228d30171f84b762c55cb716df56ec37R1441))

---

It would be nice to get strings back out of `powerset()` if you pass them in, and this applies to other tools like `chunked()` as well. If we added a `post_group_func` or something to those tools that defaults to `''.join`, that might be neat?

---

The "generate all of the windows" aspect of `subsequences()` is possibly generally useful. I suspect there may be a more efficient way of doing that than calling `windowed()` on all possible lengths, though?

---
If there are repeated elements in the argument `powerset()`, you can get repeated output. Is there an efficient algorithm to generate the same output as `set(powerset(iterable))` that doesn't produce the duplicates and throw them away? (the same way `distinct_permutations()` is much more efficeint than `set(permutations(iterable))`)

**Comment by pylang** [comment]
Your feedback is appreciated.

No problem.  I'll just share one thing about using `powerset` is that it is not obvious (at least to me at first) that the `powerset` yields non-consecutive subsequences.  I also learned from some Haskell folks, the term [powerset](https://en.wikipedia.org/wiki/Power_set) in Python is a misnomer since the result is not a true mathematical/Python set (the elements are partially ordered and replicates are permitted, e.g. `powerset("abca")` or `powerset("111")`).  Thus some visitors, let's say from the Haskell world, may not be inclined to use this tool to get a list of subsequences.

FYI - anyone interested in the future, I have have solved an handful of sample problems with this tool (all written up, just not yet shared).  Available upon request.

---

I would have to review the partitions algorithm a bit more.  Regarding general types, what came to mind would be a generator that returned groups like the following:

Instead of `partition(5)`:

    1 +  1 +  1 +  1 +  1
    1 +  1 +  1 +  2
    1 +  1 +  3
    1 +  2 +  2
    1 +  4
    2 +  3
    5

Maybe `parts(iterable)` where `iterable = (1 for _ in range(5))` or some other input (strings, iterators):

    (1,),  (1,),  (1,),  (1,), (1,)
    (1,),  (1,),  (1,),  (1,, 1,)
    (1,),  (1,),  (1, 1, 1,)
    (1,),  (1, 1),  (1, 1)
    (1,),  (1,, 1, 1, 1,)
    (1, 1),  (1, 1, 1)
    (1, 1, 1, 1, 1)

Followed by `starmap(sum, *parts(iterable))` to emulate the result of `partition(5)`.

---

A post-processing function would be interesting in general.  On one hand, it can save a bunch of typing. 
 On the other, since it is not the norm in `itertools`, I am inclined to stick with the convention of "let the user do their own post processing."  

If it was accepted, I'd consider having `post_group_func` default to "no post-processing" and let the user pass a function like "str.join" to act on the final result.

---

Yeah, `windowed` is just my goto regarding sliding windows, but  I think `islice` could probably substitute.  That would reduce all of the internal conditionals involved.  Good catch.

---

I think you are essentially asking is there a way to make a true `powerset`? :)  I imagine there is an implementation out there in another language, but should we make one, what do we call it?  The proper name is already taken by the `itertools` recipe. )
