### ISSUE TITLE
Any chance of changing the first_true default to None?

### ISSUE THREAD

**Issue by sk-** [erikrose/more-itertools#231]
I'm adding types stubs to more_itertools and one function I'm having issues with is first_true, as the default value is False instead of None.

The problem is that the return Type would be `Union[T, bool]`, which makes the following code invalid:

```python
element = first_true(elements, pred=...)
if element:
  # do something with element
```

See https://github.com/python/typeshed/issues/2390 where I ask if there's any idiom to express that.

But I don't think there is as `next` has the same issue.

**Comment by pylang** [comment]
Should be possible.  The only trouble is that the[legacy recipe](https://docs.python.org/3/library/itertools.html#itertools-recipes) specifies `False` as the default.


```python
def first_true(iterable, default=False, pred=None)
    ...
```

In typeshed, what does the [`_VT` substitute](https://github.com/python/typeshed/blob/master/stdlib/3/builtins.pyi#L20) mean?  Is it a placeholder to defaults?

**Comment by bbayles** [comment]
I think `None` makes more sense, but I'm disinclined to change it for this reason - the `default` parameter means this function can return anything; this should have the same type signature as `next()`.

**Comment by sk-** [comment]
@pylang `_VT` is just a type placeholder (I wonder if this is coming from value type).

@bbayles the semantics of `next` are different, as when no value is specified `StopIteration` is raised.

**Comment by bbayles** [comment]
Ah, you're right. I should have said, `first_true()` should have an [overloaded](https://mypy.readthedocs.io/en/latest/more_types.html#function-overloading) signature - one for when the `default` isn't given and one for when it is.

**Comment by OJFord** [comment]
The problem persists: whatever the type of `default` (whether explicit or not) the actual return value is more specifically `default` itself, not simply a value of type `type(default)`.

**Comment by sk-** [comment]
@OJFord Agree, however having the default `default` being `None` you could annotate the function as:

```python
@override
def first_true(iterable: Iterable[T], pred: Optional[Callable[[T], bool]] = None) -> Optional[T]:
@override
def first_true(iterable: Iterable[T], default: VT, pred: Optional[Callable[[T], bool]] = None) -> Union[T,VT]:
```

which allows you to use the pattern I posted in the original post. The crux being that the `NoneType` has exactly one value and type checkers know about it.

Note that Mypy is working on having something that would be useful in this case. See https://github.com/python/typeshed/issues/2390#issuecomment-413586900

**Comment by bbayles** [comment]
Thanks for keeping on this, and especially for contributing type hints for `more-itertools`.

In general I think considerations for Python's optional type checking shouldn't prompt one to change working code, and I agree with the comment referenced above that handling this type of function signature should be something that Mypy should be able to do.

That said, I've decided you're right and that `None` is a better default return type for the function. I'll change it for the next release.

It's a bit of a small thing to change the major release number for; if someone can find an example of code that relies on the `False` behavior I will make sure to do that.
