### ISSUE TITLE
Chainable tools

### ISSUE THREAD

**Issue by pylang** [erikrose/more-itertools#250]
I heard about these two libraries with chained methods on an object that wraps an iterable.  

1. [Repo](https://github.com/sixty-north/asq) `aqk`
1. [Repo](https://github.com/olirice/flupy) `flupy`

From flupy

```python
pipeline = flu(count()).map(lambda x: x**2) \
                       .filter(lambda x: x % 517 == 0) \
                       .chunk(5) \
                       .take(3)

for item in pipeline:
  print(item)

# Returns:
# [0, 267289, 1069156, 2405601, 4276624]
# [6682225, 9622404, 13097161, 17106496, 21650409]
# [26728900, 32341969, 38489616, 45171841, 52388644]
```

What are your thoughts on doing something similar in `more_itertools` - perhaps a `Chainable` or `Pipeline` object that wraps an iterable and gives serial dotted access to close to all of the tools in the library?

**Comment by rovyko** [comment]
Is there any performance benefit to chaining methods?

**Comment by MSeifert04** [comment]
Just for reference: I also have them in my library (https://iteration-utilities.readthedocs.io/en/latest/iterable.html). Which one to use is probably a matter of taste and style. 

I experimented with 3 classes (normal iterable, infinite iterable and manyiterables). The reason for the distinction between the normal and inifinite iterable was that the whole class of "reduce"-like functions shouldn't be applied to infinite iterables. Not sure if that was a good decision though 😓 

I personally prefer the chained style, but if you have both as alternatives everyone can choose what he/she likes best.

**Comment by pylang** [comment]
I was playing around with ways to generalize this idea.  I have prototyped a chainable class that:

- @rovyko auto-attaches functions to the Chainable object.  This would minimize having to modify the existing functions in the library, e.g. decorators.
- @MSeifert04 I chose to wrap around one iterable.   All other args get passed into the chained methods.  I'm still working out how to handle "zero-iterable" signatures such as `iterate(func, start)`. 

The catch is that it only works with annotated functions, which is a limitation at the moment, but I think someone else is trying to [add type stubs](https://github.com/erikrose/more-itertools/issues/231) to the library, so this approach may work in the future.  

However, I would ideally like to attach *any* function (without or without annotations), including builtins.  That part is tricky because it's nearly impossible to figure out types from a function signature without annotations.  I'll share code later if this is a good fit.  The generalized approach may merit a separate library.

**Comment by bbayles** [comment]
I could swear we had a similar discussion in an earlier issue, but it didn't jump out at me in a glance through the list.

I don't get the appeal of this - why are dots better than parens? However, I'll certainly entertain an addition that doesn't entail re-writing all the existing tools.

**Comment by pylang** [comment]
I can not argue that a chained approach supplants the status quo.  It's just another way to do a similar thing, analogous to  [`make_decorator`](https://github.com/erikrose/more-itertools/pull/187) is another way to reuse a tool.

The most I can say is that chaining allows someone to "keep typing in the right direction", while parens (without assist from an editor) requires clicking back and forth to encase an object.  A minor nuisance the grows with more and more nested calls e.g. `take(chunk(filter(map(obj))))`.  Consequently, as pointed out, readability improves as it reads more naturally from one side to the other, e.g. left to right rather than inside to outside.

That latter point may not be a strong enough reason to include chainable pipelines here, but  since tools  are more prone to these nested implementations in general, I suggested it here.  Ideally, it would be nice to chain *any* function to a pipeline so that we could also attach builtins (`map`, `filter`, etc) and tools from other libraries (`itertools` and even third-parties) in a pipeline.

**Comment by pylang** [comment]
I'm thinking of closing this until type annotations are added to the library.   It may be more fitting after the library becomes exclusively Python 3, but I'll wait a bit to see if there is any more intrigue.

Here is one of the prototypes I worked up if anyone wants to explore the idea further:

<details>
<summary>
Boilerplate
</summary>

**Given**
```python
import inspect
import itertools as it
from typing import Iterable, Callable
```

Helpers

```python
# Type creep
def _attach_functions(obj):
    """Return None; attach global annotated functions to an object."""
    callables = {
        k:v for k, v in globals().items() if inspect.isfunction(v) 
        and v.__annotations__ 
        and not k.startswith("_")
    }
    for x in callables.values():
        obj.attach(x)
        print(f"  INFO: Attached '{x.__name__}' ...")

def _view_functions(obj):
    """Return function name attached on the object."""
    return [x for x in dir(obj) if not x.startswith("_")]
```

Annotated functions

```python
def double(iterable: Iterable):
    """Return an iterator of doubled items."""
    return (x*2 for x in iterable)


def triple(iterable: Iterable):
    """Return an iterator of tripled items."""
    return (x*3 for x in iterable)


def stringify(iterable: Iterable, key: Callable=None):
    """Return an iterator of stringed items."""
    if key is None:
        key = lambda x: x
    return (key(str(x)) for x in iterable)
```
</details>


**Code**

```python
class FooB:
    
    def __init__(self, iterable):
        self._iterable = iter(iterable)
             
    def __iter__(self):
        return self
    
    def __next__(self):
        return next(self._iterable)
    
    def attach(self, func):
        """Attach a function to the class."""
        fn_name = func.__name__
        
        def _new_method(**kwargs):
            self._iterable = func(self._iterable, **kwargs)
            return self
        
        _new_method.__name__ = fn_name
        #self.__class__.double = _new_method
        setattr(self, fn_name, _new_method)
        
```

**Demo**

```python
>>> iterable = range(10)
>>> foo = FooB(iterable)
>>> _attach_functions(foo)
>>> print("Methods on 'foo':", _view_functions(foo))

>>> list(foo.double().triple().stringify())
['0', '6', '12', '18', '24', '30', '36', '42', '48', '54']
```

The principle is shown where a chainable instance wraps an iterable and attaches functions found in the global namespace.  I'm exploring how to generalize this to functions with more complex signatures, but the idea is here - drop in a class that auto-attaches functions from the `more_itertools` library via type annotations.
