### ISSUE TITLE
Drop Python 2.7 support by 2020

### ISSUE THREAD

**Issue by bbayles** [erikrose/more-itertools#253]
It's almost 2019, which will be the last year with any releases that explicitly support Python 2.7. See [here](https://python3statement.org/) for some information on motivation.

What this means:
* I'll continue to accept additions that require Python 2-specific code throughout 2019
* At the end of 2019 I'll make a final Python 2.7-compatible release
* After that release I will make issues for making use of Python 3-only features, like `yield from`
* I'll remove `six` from the requirements and remove the places where it's used
* I'll accept PRs that change existing tools to use Python 3-only features
* I'll accept PRs that add new tools with Python 3-only features

If someone wants to make a fork targeting older Python versions they are of course welcome to; if requested I will provide a link in the docs.

**Comment by bbayles** [comment]
If now is good enough for numpy, it's good enough for me. I'll open a PR to drop Python 2-isms - let me know if you see any I missed.

Anybody have any opinions on using `yield from` instead of `return`, for tools that give back an iterator? For example, [this function](https://github.com/erikrose/more-itertools/blob/c5088d2f2af42b5ed5429c4d92cc5a83b7ab25b2/more_itertools/more.py#L2275) returns, but could `yield from` instead.

**Comment by jaraco** [comment]
I would prefer return where suitable _unless_ you do in fact want the deferral of behavior preceding the yield from.

**Comment by erikrose** [comment]
I generally reach for ‘yield from’ only when it can eliminate a ’for’ loop.

**Comment by hugovk** [comment]
🎆https://github.com/erikrose/more-itertools/pull/268 has been merged.

Should this issue be closed, or kept open for visibility?

**Comment by bbayles** [comment]
Ah, yes. I'll close this when I merge #271 and make a release.

**Comment by bbayles** [comment]
And it's out. Many thanks!
