### ISSUE TITLE
Add type annotations

### ISSUE THREAD

**Issue by Tadaboody** [erikrose/more-itertools#262]
I'd like to implement [PEP 484](https://www.python.org/dev/peps/pep-0484/) type annotations and distribute them as detailed in [PEP 561](https://www.python.org/dev/peps/pep-0561/). Do you think this is a good idea for the project?

**Comment by Tadaboody** [comment]
If it is, should we make a separate type stub like the ones in [typeshed](https://github.com/python/typeshed) or implement them inside the existing source?

**Comment by pylang** [comment]
I think it's a great idea.  Type annotations could introduce new tools (e.g. https://github.com/erikrose/more-itertools/issues/250).  Adding stubs would be more favorable than annotating the library directly.  Be aware, there has been some talk about add types in the past (https://github.com/erikrose/more-itertools/issues/231), but I'm not sure about the status.

**Comment by Tadaboody** [comment]
I'll open a pull request, adding them iteratively over time. If @sk- is still interested I'll give him write access to that branch

**Comment by bbayles** [comment]
Thanks for looking into this. I like the PEP 561 method while Python 2 support is on offer.

The PR looks like a good start. I'd like there to be tests that run in Travis that checks the types, though?

**Comment by Tadaboody** [comment]
Of course testing is in order. I think running a type checker like mypy on the existing suite will both check the annotations and help fix bugs that the tests might have

**Comment by Tadaboody** [comment]
Do you support splitting up the existing files like I started doing in the PR?

**Comment by bbayles** [comment]
> Do you support splitting up the existing files like I started doing in the PR?

Ah, no - not really. That grouping is for the docs, no need to reproduce it elsewhere.

**Comment by sk-** [comment]
@Tadaboody Feel free to add the annotations we are using so far:

```python
from typing import overload, Callable, Dict, Hashable, Iterable, List, Optional, TypeVar

_T = TypeVar('_T')
_U = TypeVar('_U')
_V = TypeVar('_V')
_H = TypeVar('_H', bound=Hashable)


def chunked(iterable: Iterable[_T], n: int) -> Iterable[List[_T]]: ...


@overload
def map_reduce(iterable: Iterable[_T], keyfunc: Callable[[_T], _H]) -> Dict[_H, List[_T]]: ...
@overload
def map_reduce(iterable: Iterable[_T], keyfunc: Callable[[_T], _H], valuefunc: Callable[[_T], _U]) -> Dict[_H, List[_U]]: ...
@overload
def map_reduce(iterable: Iterable[_T], keyfunc: Callable[[_T], _H], *, reducefunc: Callable[[List[_T]], _U]) -> Dict[_H, List[_U]]: ...
@overload
def map_reduce(iterable: Iterable[_T], keyfunc: Callable[[_T], _H], valuefunc: Callable[[_T], _U], reducefunc: Callable[[List[_U]], _V]) -> Dict[_H, _V]: ...


@overload
def unique_everseen(iterable: Iterable[_T]) -> Iterable[_T]: ...
@overload
def unique_everseen(iterable: Iterable[_T], key: Callable[[_T], _U]) -> Iterable[_T]: ...


@overload
def first_true(iterable: Iterable[_T], *, pred: Optional[Callable[[_T], bool]] = None) -> Optional[_T]: ...
# Technically the default value could be of any type, but that is a strange use case and would make
# the signature to return a Union[_T, _U] which is discouraged by mypy, as afterwards, the only
# thing you could do is to do an isinstance check.
@overload
def first_true(iterable: Iterable[_T], default: _T, pred: Optional[Callable[[_T], bool]] = None) -> _T: ...
```

**Comment by bbayles** [comment]
The newest release is Python 3-only, so if that makes it easier to finish PR https://github.com/erikrose/more-itertools/pull/263, I'm open to the type annotations being in the main source now.
