### ISSUE TITLE
flatmap

### ISSUE THREAD

**Issue by gsakkis** [erikrose/more-itertools#266]
How about adding `flatmap`, a common functional transformation? Granted, the implementation is trivial (`chain.from_iterable(map(f, iterable))`), but so are many others included already.

**Comment by bbayles** [comment]
Thanks for the note.

I think I like just having `flatten` and `map` - if you want `flatmap`, just to `flatten(map(f, iterable))`. `flatten` does the `chain.from_iterable()` thing.
