### ISSUE TITLE
Add another substrings function

### ISSUE THREAD

**Issue by rominf** [erikrose/more-itertools#277]
I'm proposing to add another `substrings` function. Here is the implementation:
```python
def substrings_new(string, with_indexes=False):
    return ((string[i:i + length], i, i + length) if with_indexes else string[i:i + length]
             for length in range(len(string), 0, -1)
             for i in range(len(string) - length + 1))
```
Differences with `substrings`, which is already included:
1. Downside: this function requires the argument to be subscribable.
2. Order: my version returns longest substrings first. I think this is a more suitable behavior for NLP tasks.
3. Indexes can be included. Indexes are useful for replacing substrings in the original string, which is also good for NLP tasks.
4. The function returns normal strings, not the list of strings of length 1. No need to do expensive `join`.
5. Implementation: it's smaller and IMHO more readable.
6. Speed:
```python
In [1]: a = ' '*100

In [2]: %timeit list(substrings(a))
1.9 ms ± 41.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [3]: %timeit [''.join(substring) for substring in substrings(a)]
3.66 ms ± 171 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [4]: %timeit list(substrings_new(a))
1.3 ms ± 46.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

The only problem is what to do with 2 similar, but different functions in the library. That's why this is an issue, but not PR.

PS: I'm currently using this function in https://github.com/rominf/profanity-filter, so this function is useful.

**Comment by bbayles** [comment]
Many thanks for the writeup.

I can see the utility of giving the indexes and limiting this just to slice-able things, or just strings.

If you make a PR with this, call it `substring_indexes`, and make it so it _always_ includes the indexes, I think I'd merge that.

**Comment by rominf** [comment]
OK. I will do it tomorrow. But maybe you meant `substrings_indexes`?

**Comment by pylang** [comment]
`substrings` returns smallest to largest subitems.  The OP proposes largest to smallest.  I think there should be some congruence between outputs.  Perhaps `substrings` and the OP would do well with a `reverse=True` parameter, yielding the larger subitem first.  This helps to short-circuit "longest ..."-type problems.

Implementating a reverse flag here should be simple, adding the following:

```python
def substrings_new(seq, reverse=False):
    if reverse:
        range_ = reversed(range(len(seq)))
    else:
        range_ = range(len(seq))
    ...
```
replacing `range(len(string), 0, -1)` with `range_`.


@rominf I suggest substituting `string` with `sequence`.  Also, make sure you are getting actual [substrings](https://en.wikipedia.org/wiki/Substring).  The definition is specific.

Related post: #229
