### ISSUE TITLE
Unable to return zero or one element, ValueError on more

### ISSUE THREAD

**Issue by jaraco** [erikrose/more-itertools#281]
I have a function that has this docstring:

"""
Return the first element from the iterable, if present, or None. Raises a ValueError if more than one element is present.
"""

I thought for sure more_itertools.one or more_itertools.first would satisfy this use-case, but neither does.

`one` fails the use-case because it only raises exceptions on `too_short` or `too_long`. `first` fails because it doesn't do any checks on the iterable after.

I wonder if `one` could be extended to accept values for `too_short` and `too_long` that aren't exceptions. If they are exceptions, raise them, otherwise return that value.

Then, one could write:

```
one(iterable, too_short=None, too_long=ValueError("Too many items"))
```

**Comment by bbayles** [comment]
What do you think of [this implementation](https://github.com/erikrose/more-itertools/compare/one-extended?expand=1)?

**Comment by erikrose** [comment]
FWIW, I think I've seen this spelled as `only(iterable)` somewhere before—in case you call it so often that you want a shorter spelling. PEAK did this all the time for singleton DB queries: so much that Philip overrode the `~` operator to mean that.

**Comment by jaraco** [comment]
That implementation looks good. I probably would avoid the `_marker` and simply supply the default exceptions as the defaults for the parameters, but I understand why you may not want to do that (syntax is hard to make beautiful).

Then, one could have `only()` with `only = functools.partial(too_short=None)`.

One consideration you may want to make - because an explicit `None` now means something different, this may be considered a backward-incompatible change, if a caller was explicitly passing the default to get the default behavior. Probably unlikely, but worth considering.

**Comment by bbayles** [comment]
https://github.com/erikrose/more-itertools/pull/285 adds `only()` as a separate function. That seems easier than changing compatibility, and if you're going to use it with `partial()` anyway...
