### ISSUE TITLE
Shared iterator

### ISSUE THREAD

**Issue by pylang** [erikrose/more-itertools#288]
I saw the implementation of [this post](https://stackoverflow.com/a/55762535/4531270) and thought a similar tool might be useful here.

**Problem**

You have a generator and you consume a result that you wish to share with other clients.

If the iterator is large, rather than `tee`ing several copies of the same iterator, the post implies sharing the state of the generator with all of its "subscribers."

**Comment by bbayles** [comment]
Hmm, I'm inclined to [this answer](https://stackoverflow.com/a/55804162/353839). You can `tee` multiple times, and you'll get a clone that starts from the position of the farthest-along copy.

In fact, the linked interpretation uses this as a demonstration:

```python
# test it:
infinite_stream = [1, 2, 3, 4, 5]
factory = generators_factory(infinite_stream)
gen1 = factory()
gen2 = factory()
print(next(gen1)) # 1
print(next(gen2)) # 1 even after it was produced by gen1
print(list(gen1)) # [2, 3, 4, 5] # the rest after 1
```

But you can just do this with `tee`:

```python
>>> from itertools import tee
>>> stream = [1, 2, 3, 4, 5]
>>> gen1, = tee(stream, 1)
>>> gen2, = tee(stream, 1)
>>> print(next(gen1))
1
>>> print(next(gen2))
1
>>> print(list(gen1))
[2, 3, 4, 5]
```

What am I missing?

**Comment by pylang** [comment]
I see now the linked answer basically altered the return value of `tee` and turned `itertools.tee(base)` into a callable.  Yes, the answer you posted came after this suggestion and seems the way to go.  Closing.
