### ISSUE TITLE
New itertool: window

### ISSUE THREAD

**Issue by buchanae** [erikrose/more-itertools#29]
How about adding a sliding window itertool?

There are multiple implementations that trade off on things like memory consumption/speed/etc, but here's a version that's worked fine for me

```
from collections import deque

def window(seq, n=2):
    it = iter(seq)
    win = deque((next(it, None) for _ in xrange(n)), maxlen=n)
    yield win
    append = win.append
    for e in it:
        append(e)
        yield win
```

**Comment by bbayles** [comment]
Fixed in #63. Thanks!
