### ISSUE TITLE
getting 'SyntaxError: invalid syntax'

### ISSUE THREAD

**Issue by MaximLeyenson** [erikrose/more-itertools#295]
- [x] a detailed description of the bug or suggestion
- [ ] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

I am trying to run [Stapler](https://github.com/hellerbarde/stapler) after switching to Linux Mint. 
Stapler depens on Python 2 and more-itertools, I have python-more-itertools  3.2.0-2:

`# apt list *more-itertools*`
`python-more-itertools/bionic,bionic,now 3.2.0-2 all [installed]  `

(though `$pip list` gives `more-itertools (7.0.0)` ; I do not know how they are enumerated)

I am encountering  

```
$ stapler -h
Traceback (most recent call last):
  File "/usr/local/bin/stapler", line 11, in <module>
    load_entry_point('stapler==0.3.3', 'console_scripts', 'stapler')()
  File "/usr/local/lib/python2.7/dist-packages/stapler-0.3.3-py2.7.egg/staplelib/__init__.py", line 11, in main
    import stapler
  File "/usr/local/lib/python2.7/dist-packages/stapler-0.3.3-py2.7.egg/staplelib/stapler.py", line 9, in <module>
    from . import commands, CommandError
  File "/usr/local/lib/python2.7/dist-packages/stapler-0.3.3-py2.7.egg/staplelib/commands.py", line 10, in <module>
    import more_itertools
  File "build/bdist.linux-x86_64/egg/more_itertools/__init__.py", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/more_itertools-7.0.0-py2.7.egg/more_itertools/more.py", line 333
    def _collate(*iterables, key=lambda a: a, reverse=False):
                               ^
SyntaxError: invalid syntax
```

I have installed Stapler with

 ```
 $ sudo  apt install python-setuptools 
  $ sudo apt install python-more-itertools
  $ git clone https://github.com/hellerbarde/stapler
  $ cd stapler
  $ sudo python setup.py install
```

There is no file 

 ` "/usr/local/lib/python2.7/dist-packages/more_itertools-7.0.0-py2.7.egg/more_itertools/more.py"`

on my system, though there is a file (not a folder)

```
$ file /usr/local/lib/python2.7/dist-packages/more_itertools-7.0.0-py2.7.egg

/usr/local/lib/python2.7/dist-packages/more_itertools-7.0.0-py2.7.egg: Zip archive data, at least v2.0 to extract
```

Running pytest:

```
======== test session starts  ===============================
platform linux2 -- Python 2.7.15rc1, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: /home/leyenson/island/text-files/logins, inifile:
collected 0 items      
```                                                                                                               
System:

`Linux .. 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Thank you!

**Comment by bbayles** [comment]
`more-itertools` doesn't support Python 2 anymore. You can use version 5.0.0 (`pip install more-itertools==5.0.0`), which was the last version that worked on Python 2.7.

Stapler ought to change their [setup.py](https://github.com/hellerbarde/stapler/blob/master/setup.py#L16) to indicate < 6.0.0.

**Comment by MaximLeyenson** [comment]
> `more-itertools` doesn't support Python 2 anymore. You can use version 5.0.0 (`pip install more-itertools==5.0.0`), which was the last version that worked on Python 2.7.
> 
> Stapler ought to change their [setup.py](https://github.com/hellerbarde/stapler/blob/master/setup.py#L16) to indicate < 6.0.0.

Thank you! Will try to downgrade more-itertools manually. Maxim
