### ISSUE TITLE
Set partitioning

### ISSUE THREAD

**Issue by ktbarrett** [erikrose/more-itertools#296]
I would like to the library include a function that implements partitioning of a set N-ways that does not preserve order (that's how it differs from `partitions`).

The 2-way set partitions of `range(4)` are
```python
((0,), (1, 2, 3))
((1,), (0, 2, 3))
((2,), (0, 1, 3))
((3,), (0, 1, 2))
((0, 1), (2, 3))
((0, 2), (1, 3))
((0, 3), (1, 2))
```

If this is desired, I already have an implementation of `integer_partitions` and `set_partitions` that yield lexicographically ordered partitions.

**Comment by bbayles** [comment]
Please do post your implementations, yes.

**Comment by ktbarrett** [comment]
See #297
