### ISSUE TITLE
Some good ideas in http://hackflow.com/blog/2013/10/13/functional-python-made-easy/

### ISSUE THREAD

**Issue by erikrose** [erikrose/more-itertools#30]

**Comment by erikrose** [comment]
Since I wrote this, I've had a chance to use funcy in my project DXR, and I've regretted it. It's been memory-inefficient and clumsily coded. Still, there may be some ideas to salvage.

**Comment by bbayles** [comment]
I think we've got most of what's in the blog post covered; closing this. I'll read through more funcy docs and add issues or PRs for specific ideas that seems applicable.

**Comment by erikrose** [comment]
Sounds good! You're doing excellent work. Let me know when you want to do another release.

**Comment by bbayles** [comment]
Thanks!

Re: New release, I'll make a PR for it and ping you. My plan is to finish off the open PRs first, and maybe the open issues.
