### ISSUE TITLE
`set_partitions` speed

### ISSUE THREAD

**Issue by jferard** [erikrose/more-itertools#300]
I recently needed to get all partitions of a list in `k` groups (to answer [this question](https://stackoverflow.com/questions/56987469/how-to-find-anagrams-using-3-words-in-a-text-having-a-list-of-words/57171036#57171036)). I didn't find `set_partitions` in my installed version of `more_itertools`, hence I implemented [a simple and straightforward version](https://stackoverflow.com/a/57171036/6914441). Here's a slightly modified version:

    def set_partitions2(S, k):
        S = list(S)
        if len(S) < k or k <= 0:
            raise ValueError("Can't partition {} in {} elements".format(S, k))
        elif k == 1:
            yield [S]
        elif len(S) == k:
            yield list(map(list, S))
        else:
            e, *M = S
            for p in set_partitions2(M, k-1):
                yield ([e], *p)
            for p in set_partitions2(M, k):
                for i in range(len(p)):
                    yield list(p[:i]) + [[e] + p[i]] + list(p[i+1:])

As you can see:

* it returns tuples of lists instead of tuples of tuples;
* the tuples and the groups inside the tuples are not ordered the same way as `more_itertools.set_partitions`;
* there is no `k=None` version.

But the result is equivalent . Examples:

```
list(set_partitions2("abcd", 3))
# [(['a'], ['b'], ['c', 'd']), (['a'], ['b', 'c'], ['d']), (['a'], ['c'], ['b', 'd']), [['a', 'b'], ['c'], ['d']], [['b'], ['a', 'c'], ['d']], [['b'], ['c'], ['a', 'd']]]

list(set_partitions("abcd", 3))
# [(('a',), ('b',), ('c', 'd')), (('a',), ('c',), ('b', 'd')), (('a',), ('d',), ('b', 'c')), (('b',), ('c',), ('a', 'd')), (('b',), ('d',), ('a', 'c')), (('c',), ('d',), ('a', 'b'))]
```

Out of curiosity, I checked the speed of both version, and my version is a lot faster:

    print (timeit.timeit(lambda: list(set_partitions2("abcdefghi", 4)), number=100))
    # 0.6860678209995967
    print (timeit.timeit(lambda: list(set_partitions("abcdefghi", 4)), number=100))
    # 17.434939999000562

And

    print (timeit.timeit(lambda: list(set_partitions2("abcdefghiklm", 4)), number=10))
    5.268347465000261
    print (timeit.timeit(lambda: list(set_partitions("abcdefghiklm", 4)), number=10))
    165.6531076650008

I know that `set_partitions` is very young in `more_itertools` and is maybe a work in progress, thus I didn't make a pull request (I don't want to be rude!), but I would be glad to improve my code (comments, ...) and to make one if you think it worthes it.
(Any comment from @ktbarrett is welcome.)

**Comment by bbayles** [comment]
A PR is welcome - if you can make the output types match and show the tests still pass, I would take this for the next release. Thanks!

**Comment by jferard** [comment]
(1) I think the output types are wrong in both implementations.

*Explanation:* one element of the partitions of "abcd" in 3 groups is: `(['a'], ['b', 'c'], ['d'])` in my version and `(('a',), ('d',), ('b', 'c'))` in the current version (see my first post). Both are wrong, because these are the same partition, and should be a set: `{('a',), ('d',), ('b', 'c')}` (obviously, tuples are better than lists as elements of a set). But `{('a',), ('d',), ('c', 'b')}` would also be a correct partition.

(2) The current test are too strict and would reject a correct iterator on partitions because of (1) and also because the current tests [check the order of partitions ](https://github.com/erikrose/more-itertools/blob/master/more_itertools/tests/test_more.py#L2485) in the iteration, but that is totally implementation dependent (and the [docstring](https://github.com/erikrose/more-itertools/blob/master/more_itertools/more.py#L2404) states that "Set partitions are not order-preserving").

Hence I can't provide a PR that passes the tests because I think tests are too strict!

Three remarks:

* In my version, the order inside a set is preserved (but that doesn't matter either).
* BTW, a test could take advantage of: https://en.wikipedia.org/wiki/Stirling_numbers_of_the_second_kind#Table_of_values.
* my version does not implement the version where `k=None` (but I could try to add this).

**Comment by ktbarrett** [comment]
* Speed is more important than ordering IMO, remove the lexical ordering test, this implementation is better.
* Implementing `k=None` is trivial and preserves the semantics of `partitions` which does not take a `k` (maybe it should) and simply outputs all possible `k` groupings.
* Having the result type be tuples or lists is best, sets require all elements to be hashable. That assumption is fine if your set is `"abcd"`, but not great if it's something more complex.
* Expanding on that, your implementation doesn't like some 'complex' inputs. Try `set_partitions2(({1}, {2}, 3), 3)`. Kinda silly, but it should work.

To that end, I've modified your implementation.
```python
def set_partitions2(S, k=None):
    S = list(S)
    lenS = len(S)
    if k is not None and (lenS < k or k <= 0):
        raise ValueError("Can't partition {} in {} elements".format(S, k))
    def helper(S, k):
        if k == 1:
            yield [S]
        elif lenS == k:
            yield [[s] for s in S]
        else:
            e, *M = S
            for p in set_partitions2(M, k-1):
                yield ([e], *p)
            for p in set_partitions2(M, k):
                for i in range(len(p)):
                    yield p[:i] + [[e] + p[i]] + p[i+1:]
    if k is None:
        for k in range(1, lenS+1):
            yield from helper(S, k)
    else:
        yield from helper(S, k)
```
I might also separate the validity checks into two, with different error messages.

**Comment by bbayles** [comment]
I'm fine if the tests need to change for order reasons.

**Comment by jferard** [comment]
@ktbarrett :
>  Speed is more important than ordering IMO, remove the lexical ordering test, this implementation is better.
I agree

> Implementing k=None is trivial and preserves the semantics of partitions which does not take a k (maybe it should) and simply outputs all possible k groupings.
You just proved it.

> Having the result type be tuples or lists is best, sets require all elements to be hashable. That assumption is fine if your set is "abcd", but not great if it's something more complex.
You are right.

@bbayles I will make a PR based on the improvements of @ktbarrett.

**Comment by jferard** [comment]
I started coding and everything seems fine but I would need, in order to make tests more robust, a [MultiSet]( https://en.wikipedia.org/wiki/Multiset) class or function. It's not a coding problem, because something like:

    def multiset(xs):
        """Return a multiset equivalent for an iterable: every element is stored along with its cardinality"""
        return set(Counter(xs).items())

    def frozenmultiset(xs):
        """Return a multiset equivalent for an iterable: every element is stored along with its cardinality"""
        return frozenset(Counter(xs).items())

Would do the trick (need some refinement of course). But it don't know where to put this:

* in `more.py`? it can take an iterable as argument, but is not strictly an itertool;
* in `tests/more.py`? then the function/class and the tests would be in the same file - not a very good practice because a test failure in `MultisetTests` would be blocking while `MultiSet` is not part of the module;
* in another file?

Or simply fix the tests to match the current implementation and restart each time the implementation changes (frustrating to me).

**Comment by bbayles** [comment]
Thanks for taking a close look at this. I would say define the multiset in the tests file, and don't write tests for it; it's not part of the library.
