### ISSUE TITLE
split_before confuse me

### ISSUE THREAD

**Issue by Elune0syh** [erikrose/more-itertools#304]
[The docs says `split_before`](https://more-itertools.readthedocs.io/en/latest/api.html#more_itertools.split_before)
> Yield lists of items from iterable, where each list starts with an item where callable pred returns True

But why below returns
```
In [3]: list(split_before(range(1, 10), lambda n: n % 3 == 0))
Out[3]: [[1, 2], [3, 4, 5], [6, 7, 8], [9]]
```
Rather than returns
```
In [3]: list(split_before(range(1, 10), lambda n: n % 3 == 0))
Out[3]: [[3, 4, 5], [6, 7, 8], [9]]
```

What i`m got wrong ?  Thanks in advance

**Comment by bbayles** [comment]
Thanks for the note. You're right; I should change the docstring to be more accurate. No items are skipped by `split_before`.

**Comment by Elune0syh** [comment]
Thanks for your reply, it solves my question.

**Comment by isolet** [comment]
I've thought that `list(split_before('OneTwo', lambda s: s.isupper()))` will return `[[''], ['O', 'n', 'e'], ['T', 'w', 'o']]`...
