### ISSUE TITLE
Problematic combination of `consecutive_groups` and `last`

### ISSUE THREAD

**Issue by kriomant** [erikrose/more-itertools#307]
```
>>> from more_itertools import consecutive_groups, last
>>> list(map(list, consecutive_groups([1,2,10,11])))
[[1, 2], [10, 11]]
>>> list(last(consecutive_groups([1,2,10,11])))
[11]
```

**Comment by bbayles** [comment]
Ah, tricky. This is similar to the behavior of [groupby](https://docs.python.org/3/library/itertools.html#itertools.groupby).

Its docs note:
> The returned group is itself an iterator that shares the underlying iterable with `groupby()`. Because the source is shared, when the `groupby()` object is advanced, the previous group is no longer visible. So, if that data is needed later, it should be stored as a list...

Using `last()` is like consuming the returned iterable out of order, so we see some strange behavior. I will add a note to the docs.

**Comment by bbayles** [comment]
Added in PR #38. Thanks!
