### ISSUE TITLE
More informative exception message for `only`

### ISSUE THREAD

**Issue by gabbard** [erikrose/more-itertools#312]
Our team is thinking of replacing our use of some internal utility methods with `more-itertools`. Something we would miss, though, is that in some cases our methods give helpful debugging information. 

For example (as noted by my colleague @berquist ), compare [`get_only`](https://github.com/isi-vista/vistautils/blob/7eb87c06d3dc31d8c29f43d932ef6b834500c3f2/vistautils/collection_utils.py#L8) to [`only`](https://github.com/erikrose/more-itertools/blob/111d6deb8080040f8ec28db32eeb44b61238d860/more_itertools/more.py#L2523):

```
x = [1, 2, 3]
get_only(x)
ValueError("Expected one item in iterable but got multiple: [1, 2, 3]")
only(x)
ValueError("too many items in iterable (expected 1)")
```

The extra information provided by the former is often enough to determine the fix for a bug simply by reading the exception message.

The downside of `get_only`'s approach is that it can produce large error messages for collections with large, complex objects with bulky `__repr__`s. (collections with many elements are not a problem because we limit the number of elements we print).    In our case at least, the trade-off seems worthwhile.

Is adding a more informative message along these minds something that would be useful to `more_itertools`?  (another option: `only` currently takes an argument `too_long` which is `raise`d on error if specified.  We could allow making `too_long` a `Callable` which is called to generate the exception on failure).

**Comment by MSeifert04** [comment]
How would that work for iterators/generators (as opposed to sequences)?

E.g. What would be the output for:

```
x = (i for i in [1, 2, 3])
get_only(x)
```

**Comment by rgabbard** [comment]
@MSeifert04 : Our implementation of `get_only` pulls the first two values from the input `Iterable`, using a sentinel value as the default in our call to `next` for the second value.  This means that in the failure condition we have access to at least two values from the sequence and/or generator.  Our current implementation checks if the input `Iterable` is `Sized`; if so, it gives the error above. If not (e.g. the input is a generator), it plays it safe and just uses the two values it has extracted in the error message like this:
```
ValueError("Expected one item in sequence but got at least 'foo', 'bar', and possibly more.")
```

Supporting an error message like this does require using a sentinel value implementation for `only` rather than an exception-based approach; I would be happy to write up a quick benchmark to determine if there is a performance difference.

**Comment by bbayles** [comment]
I'd be happy with a PR that shows the first two items. Something like `Expected one item in iterable, but got more: ('foo', 'bar', ...)`.

**Comment by bbayles** [comment]
For what it's worth, `too_long` can do the thing you want (for sequences):

```
>>> from more_itertools import only
... 
... x = [1, 2, 3]
... too_long = RuntimeError("Expected one item in iterable but got multiple: {}".format(x))
... only(x, too_long=too_long)
Traceback (most recent call last):
  File "<pyshell#2>", line 5, in <module>
    only(x, too_long=too_long)
  File "/home/bo/Code/more-itertools/more_itertools/more.py", line 3021, in only
    raise too_long or ValueError(  # type: ignore
RuntimeError: Expected one item in iterable but got multiple: [1, 2, 3]
```

**Comment by gabbard** [comment]
@bbayles : Thanks! I'll work on such a PR and submit it sometime soon.

The problem with `too_long`'s current approach is that you have to pay the price of constructing the exception (which might be quite expensive given the string formatting involved) even on the (presumably expected) path when there is only one element.  This is what motivated the suggestion above of allowing the user to supply a `Callable` which is invoked to create the exception only when the exception in fact needs to be called.  I would be happy to submit a (separate) PR for this as well, if it is of interest.

**Comment by bbayles** [comment]
Let's go with the first two items thing. Thanks!

**Comment by gabbard** [comment]
@bbayles : PR is ready for review in https://github.com/erikrose/more-itertools/pull/313 .

**Comment by bbayles** [comment]
Many thanks!
