### ISSUE TITLE
Add not_none

### ISSUE THREAD

**Issue by gabbard** [erikrose/more-itertools#315]
It would be convenient to have a function `non_none` which takes an `Iterator`/`Iterable` and returns another which skips all elements which are `None`, similar to e.g. Kotlin's [`filterNotNull`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.sequences/filter-not-null.html). 

This can already be achieved by:
```python
filter(lambda x: x is not None, sequence)
```

or by a generator expression like

```python
(x for x in seq if x is not None)
```

but those are bulky and hard to read when composed with other sequence operations, such as:

```python
def extract_if_possible(x) -> Optional[T]:
   ...

extracted_items = filter(lambda x: x is not None, map(seq, extract_if_possible))
extracted_items = (x for x in map(seq, extract_if_possible) if x is not None)
extracted_items = non_none(map(seq, extract_if_possible))
```

**Comment by pylang** [comment]
Many thanks on the idea.  
- I personally wouldn't mind implementing my own `non_none()` function when needed.  I don't need it often, though others may.
- Just a note, some your examples demonstrate filtering falsey values, not specifically `None`.  Is there a reason to test against `None` in particular?
- [PEP 505](https://www.python.org/dev/peps/pep-0505/) has been revisited lately to bring null-aware operators to Python.  If the PEP was accepted, could such a feature address your need?

**Comment by bbayles** [comment]
Not a bad suggestion! However, I'm disinclined to add this, as there are clear one-liners that do the same thing.

**Comment by gabbard** [comment]
@pylang : Thanks for the pointer to PEP 505!  The null-aware operators in Kotlin make it (in my opinion) an extremely pleasant language to code in, so it would be great if those came to Python. The features in PEP 505 would not address this problem directly, but both PEP 505 and `non_none` would see much heavier use in code which has lots of functions returning `Optional[Foo]`s.

You are correct about the error in my examples; I've corrected them.  This is a good illustration of why I think it's useful to have this in a library even though it is simpler - it's easy to screw up! :-)

Anyway, @bbayles , thanks for the consideration!
