### ISSUE TITLE
Improve difference

### ISSUE THREAD

**Issue by Jabbey92** [erikrose/more-itertools#342]
I was reading the source for `difference` and it seems using `starmap` and reversing the arguments to the `zip` would be an improvement over the current `lambda`.

**Consideration**

    def difference(iterable, func=sub, *, initial=None):
        a, b = tee(iterable)
        try:
            first = [next(b)]
        except StopIteration:
            return iter([])
    
        if initial is not None:
            first = []
            
        return chain(first, starmap(func, zip(b,a)))

In my tests I see no difference in the output as all the lambda was doing was reversing the arguments which is unnecessary using this approach.

**Comment by bbayles** [comment]
Yes, I'd accept a PR with this. Thanks!

**Comment by Jabbey92** [comment]
Thanks for the consideration, I also want to let you know I did notice, as I was looking, that the `initial` argument defaulted to `None` which is limiting the use of `None` as an initial parameter.

I don't see it being a common case that `None` would be used there but in the chance it is, using `_marker` instead allows any value to be used. I hope that's viable/makes sense doing.

**Comment by Jabbey92** [comment]
I reverted it back to `None` I should have tested it first. It seemed right in my head until I noticed what I was doing.

**Comment by bbayles** [comment]
Thanks!
