### ISSUE TITLE
Add reservoir sampling?

### ISSUE THREAD

**Issue by tommyod** [erikrose/more-itertools#344]
Hi! Thanks for the great library! I have a proposal:

- *Reservoir sampling* algorithms sample from iterables, see [wikipedia](https://en.wikipedia.org/wiki/Reservoir_sampling).
- They can sample from iterables of unknown/infinite length.

Most Python implementations I've found are bad and/or wrong. I have some implementations of reservoir sampling with/without repetitions laying around.

Does this fit within scope of more_itertools? Would you accept a PR for algorithms like these? They are not the most commonly used algorithms, but they are used, and it would be nice to see a proper implementation in a popular Python library for working with iterables - so naturally I thought of more_itertools.

**Comment by bbayles** [comment]
Yes, I'm interested. I'd particularly like an implementation of a function with this docstring:

```python
def sample(iterable, k):
    Return a *k*-length list of unique elements chosen (without replacement)
    from the *iterable*. Used for random sampling without replacement.
    Like :func:`random.shuffle`, but works on iterables with unknown or
    infinite length.
```

**Comment by MSeifert04** [comment]
> They can sample from iterables of unknown/infinite length

Is it really possible to sample from an iterable of infinite length? It's a bit problematic because the remaining probability never goes to zero. Do you have any information (links, articles) about infinite iterable sampling? I would be very interested.

**Comment by tommyod** [comment]
You're right @MSeifert04 t, it's not really possible. My sentence was sloppy, see wikipedia for a clarification. You can sample of unknown length. If it's truly infinite I suppose the best you could do is assume a stationary probably distribution function and estimate that.

**Comment by MSeifert04** [comment]
Too bad. Thank you for the clarification.

**Comment by bbayles** [comment]
I assumed there was some probability cut-off that you could specify. If
not, amend my proposed docstring to remove "infinite."
