### ISSUE TITLE
Suggestion: Add random generators.

### ISSUE THREAD

**Issue by Jabbey92** [erikrose/more-itertools#353]
For the instances where a stream of random numbers/floating point values is needed I suggest adding ones such as below. _(Essentially efficient wrappers around the random library)_ thus replacing the need to manually create a new random number while iterating over something else. For Example:

    for element in iterable:
        rand = random.random()
        ...

Be replaced with:

    for element, rand in zip(iterable, randoms()):
        ...

I believe this is the most efficient way to do such a thing, and I also figured shadowing `random.random` and `random.randint` would be easy enough to make clear.

    from random import randint, random
    from functools import partial

    _marker = object()
 
    def randoms():
        """Yield an infinite stream of random floating point numbers
        in the range ``[0.0, 1.0]``.
    
        This function is essentially a wrapper for :func:`random.random`.
        """
        return iter(random, _marker)

    def randints(a, b):
        """Yield an infinite stream of random random integers _N_ such 
        that ``a <= N <= b``.
    
        This function is essentially a wrapper for :func:`random.randint`.
        """
        return iter(partial(randint, a, b), _marker)

**Comment by bbayles** [comment]
Hmm, I think we have a good method for this already in `repeatfunc`.

```python
>>> from random import random
... 
... from more_itertools import repeatfunc, take
... 
... take(5, repeatfunc(random))
[0.04928606964796689,
 0.5850000612684053,
 0.42845552130250053,
 0.9840364443510838,
 0.5214776201850356]
```

I would be open to adding an example using `random` module functions to the `repeatfunc` docstring, though.

**Comment by bbayles** [comment]
Closing this one, but I would take a PR with the docstring change above. Thanks!
