### ISSUE TITLE
Skipping the first n elements of an iterator

### ISSUE THREAD

**Issue by balshetzer** [erikrose/more-itertools#357]
I sometimes need to skip the first n elements of an iterator. I can do that with islice(it, n, None). I could do it with consume(it, n). I think the consume version is more readable but I can't use it inline because consume doesn't return the iterator.

What do you think of having consume return the iterator? 

Otherwise, would you support a skip(it, n) recipe? It would just map to islice(it, n, None).

**Comment by bbayles** [comment]
I think I wouldn't add something new when `islice` is right there. I would accept a PR that made `tail` skip the first `n` lines when the first argument is `-n`, a la Unix `tail`.

**Comment by balshetzer** [comment]
What about having consume return the iterator? Right now it doesn't return anything.

**Comment by bbayles** [comment]
Ah, yeah - I'd rather not modify it. For one, it's a recipe from the `itertools` docs, and I generally leave those alone (with a few exceptions). Also, if you have the iterable to pass to consume, you don't need it back?

**Comment by balshetzer** [comment]
I understand. The reason it's convenient to get it back is that it can be used inline. Like in a generator expression or list comprehension. e.g. [f(x) for x in consume(x, 1)].

I'm not crazy about the tail idea. I looked at the man page for tail and didn't see the ability to pass negatives so it's probably not universal.

So I'll close this issue and use islice.

Thanks for your help and generally for the more_itertools package. It's one of my favorites.
