### ISSUE TITLE
What is the preferred way of getting the version of more-itertools

### ISSUE THREAD

**Issue by MSeifert04** [erikrose/more-itertools#367]
A lot of packages provide some kind of variable to get the version of a package. Typically this is a `__version__` of the main module. Is there some equivalent for `more_itertools` or should one rather rely on feature detection for this library?

```
>>> import more_itertools
>>> more_itertools.__version__
AttributeError: module 'more_itertools' has no attribute '__version__'

>>> import numpy as np
>>> np.__version__
'1.17.4'

>>> import pip
>>> pip.__version__
'19.3.1'
```

In either case it would be nice if there was some sort of documentation on this.

**Comment by bbayles** [comment]
I guess I'd ask what the goal is - to check for the existence of some function, work around some bug, or what? I almost never use `__version__` in real code, but maybe I'm weird?

**Comment by MSeifert04** [comment]
In my case it was when reporting #366. I wanted to inspect the version I had installed in the interactive console without needing to check my environment.

**Comment by MSeifert04** [comment]
It's still possible to get the version with

```
import pkg_resources
pkg_resources.get_distribution("more-itertools").version
```

But that's rather hard to remember - and `__version__` seems to be some common convention.
