### ISSUE TITLE
Head and Tail

### ISSUE THREAD

**Issue by jamiecook** [erikrose/more-itertools#379]
I'm not sure if this fits with this library but I use it quite a lot so I'll put it here for judgement.

The basic concept is list decomposition by it's first element and the remainder (head and tail)

```python
def head_and_tail(iterable):     
    # type: (Iterable) -> Tuple[Any, Iterable] 
    it = iter(iterable)     
    return next(it), it 
```

Would be happy to upgrade the above into something more robust and PR if it's of interest.

**Comment by bbayles** [comment]
I think we have something similar with `spy`, right? Let me know if I'm missing some subtlety.

**Comment by jamiecook** [comment]
spy leaves the element on the second iterable

```
>>> import more_itertools
>>> a = [1,2,3]
>>> b,c = more_itertools.spy(a)
>>> print(list(b), list(c))
[1] [1, 2, 3]
>>> b,c = head_and_tail(a)
>>> print(list(b), list(c))
[1] [2, 3]
>>>
```

what I was thinking of was more analogous to the cons operator (:) for list decomposition in Haskell

```
Prelude> let a = [1,2,3]
Prelude> let b:c = a
Prelude> b
1
Prelude> c
[2,3]
```

**Comment by bbayles** [comment]
Got it. Thanks for the suggestion. I'm not inclined to add a special function for this, so I'll close the issue. Thanks again!
