### ISSUE TITLE
Unpacking unzip() fails for empty iterators.

### ISSUE THREAD

**Issue by lschmelzeisen** [erikrose/more-itertools#383]
The following use of `unzip()` is described in the docs:

```python
>>> iterable = [('a', 1), ('b', 2), ('c', 3), ('d', 4)]
>>> letters, numbers = unzip(iterable)
```

However, this will fail if `iterable` is empty:

```python
>>> letters, numbers = unzip([])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: not enough values to unpack (expected 2, got 0)
```

Unless I'm missing something this makes using `unzip()` quite unwieldy for a possibly empty  `iterable`.

What's the suggested way to deal with this case on the caller side?

 Any way the API could be changed here to make this easier for the caller?

**Comment by bbayles** [comment]
Hmm, my feeling is that `unzip` should mirror what `zip(*)` does. It would fail exactly this same way on an empty list, right?

**Comment by lschmelzeisen** [comment]
I can see the argument in that, however, for me it would be more intuitive to receive two empty iterators in `letters` and `numbers`. Of course, for something like this, `unzip()` would need to know how many values it should return.

What about adding an optional parameter `n` to `unzip()` that in case the input iterable is empty returns `n`-many empty iterables, and in case it is not empty raises an error if the number of elements in the current tuple is not equal to `n`?

I could prepare a pull request for this, if interested.

**Comment by bbayles** [comment]
I'm not sure if treating 0 specially makes sense. When you do `x, y = zip(*something)`, you're asking for two things. If there aren't two things to produce, it makes sense that an exception is raised. Similarly, `x, y, z = zip(*something)` fails with the same exception if `something` doesn't produce three things.

**Comment by lschmelzeisen** [comment]
In my view, the more common case is that you as the programmer have complete control over what `something` will contain. If you are going to use `unzip` that `something` will usually be an iterable of equally sized tuples. I don't see why the special case where `something` is empty should deserve such mirroring of the `unzip`-implementation as:

```
head, something = spy(something)
if head:
    letters, numbers = unzip(something)
    # use letters, numbers here
```

Arguably an empty iterator only consists of tuples of any required size.

Of course, the case where `something` contains different sizes tuples should still raise an exception.

**Comment by lschmelzeisen** [comment]
Another perspective would be that `unzip()` should be the reverse of `zip()`. This works generally, but fails for empty iterables:

```
>>> a, b = [], []
>>> a, b = unzip(zip(a, b))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by bbayles** [comment]
I see what you're saying. It would be nice if Python would let you unpack that way. However, I'm disinclined to change the `unzip` implementation here.

**Comment by lschmelzeisen** [comment]
Sure, it's not my code base after all :)
