### ISSUE TITLE
Add function to chunk an iterable based on a predicate

### ISSUE THREAD

**Issue by astronouth7303** [erikrose/more-itertools#39]
Add a generator that produces a generator for each chunk, where each chunk is defined by a "is first item" or "is last item" predicate.

Basic code for "is first item" idea:

``` python

def chunk_by_first(seq, pred):
    """chunk_by_first(iterable, callable) -> list, ...
    Breaks up an iterable based on a predicate: If true, break before that item.
    """
    buf = []
    for i in seq:
        if pred(i) and len(buf):
            yield buf
            buf = []
        buf.append(i)
    yield buf
```

(This implementation is of course undesirable if chunks are of considerable size. But should concisely express the idea.)

**Comment by bbayles** [comment]
@astronouth7303, I'm in favor of something (or things) like this getting into `more_itertools`. The original version that emits lists I think is good - attempting to split an iterator into sub-iterators is perilous (as you've found, and as I found in #72 mor recently).

I'd like a name that distinguishes this from `chunked` (which we're using to indicate equal-sized subsequences) and `partition` (which we're using to mean "split in two pieces"). I think `split` might work, though there is a precedent for that in the `str` builtin. Better ideas are welcome.

Below I have a `split_before` (basically the same as your original) and a `split_after` (which instead breaks after the predicate is True).

---


```python
def split_before(iterable, pred):
    buf = []
    for item in iter(iterable):
        if pred(item) and buf:
            yield buf
            buf = []
        buf.append(item)
    yield buf

def split_after(iterable, pred):
    buf = []
    for item in iter(iterable):
        buf.append(item)
        if pred(item) and buf:
            yield buf
            buf = []
    if buf:
        yield buf
```

These can have neat applications:
```python
>>> from gmpy2 import is_prime
>>> iterable = range(2, 24)
>>> list(split_before(iterable, is_prime))
[[2],
 [3, 4],
 [5, 6],
 [7, 8, 9, 10],
 [11, 12],
 [13, 14, 15, 16],
 [17, 18],
 [19, 20, 21, 22],
 [23]]
>>> list(split_after(iterable, is_prime))
[[2],
 [3],
 [4, 5],
 [6, 7],
 [8, 9, 10, 11],
 [12, 13],
 [14, 15, 16, 17],
 [18, 19],
 [20, 21, 22, 23]]
```
