### ISSUE TITLE
Sliceable peekables

### ISSUE THREAD

**Issue by erikrose** [erikrose/more-itertools#4]
I had thought to add an index to `peek()` for grabbing, say, the 2nd item (and making `peekable` stack-based), but it'd be a little awkward to have a 2nd param on there. What if, instead, peekables were sliceable?

`peekable(some_iter)[1]` would be equivalent to `peekable(some_iter).peek()`.

`peekable(some_iter)[2:8]` would also work (and look ahead, without appearing to advance the iterator).

We'd probably start off supporting only indexing and might never support negative indices.

We could also support `peekable(some_iter).get(2, 'default')` for having default fallbacks for arbitrary indexes.

**Comment by bbayles** [comment]
I like this generalization!

It makes more sense to me to have this be something like "take the remaining items in the iterator and index them as though you'd called `list()` on the iterator". That means `peekable(some_iter)[0]` is equivalent to `peeakable(some_iter).peek()`.

I've got the beginnings of this in 3cb8b59875667c012822a2108b49b1ff18472817. Positive indexing works (I think), so it should be straightforward to add in slicing with positive indexes.

**Comment by erikrose** [comment]
Your impl looks great. Good docs, especially! My onlu curiosity is whether similar situations in the stdlib raise ValueError rather than NotImplementedError.

**Comment by bbayles** [comment]
Fixed in #71.
