### ISSUE TITLE
Support chunking with a fixed number of chunks

### ISSUE THREAD

**Issue by mozbhearsum** [erikrose/more-itertools#55]
Something I do relatively often is chunk data into a certain number of chunks, rather than chunks of a certain size. I find this useful in situations where I'm parallelizing work that depends on a bottleneck (eg, database, vcs server), and I want to ensure I don't overload it if a massive amount of work comes in. I have an implementation of this in https://github.com/bhearsum/chunkify, but it seems like it might fit well into chunked.

It would require an API break, with an interface such as:
def chunked(data, chunk_size=None, total_chunks=None)

...where one (and only one) of chunk_size or total_chunks is required. chunkify also supports only returning a specific chunk, which is a bit more efficient for large lists, but not crucial.

**Comment by bbayles** [comment]
Thanks for the suggestion. I'm thinking wontfix for this, however. We have [grouper](https://github.com/erikrose/more-itertools/blob/ec7acde9e16aef7d84282d784633acc152f71e22/more_itertools/recipes.py#L187-L195), which is pretty darned close, yeah?

**Comment by bbayles** [comment]
Reviving this issue - I was wrong! `grouper()` and `chunked()` are almost identical (save for padding); I was thrown by the example for `grouper()`.

I'm thinking of a function that will evenly distribute items from an iterable into multiple sub-iterables. Something like:

```python
>>> group_1, group_2 = distribute(2, [1, 2, 3, 4, 5, 6])
>>> list(group_1)
[1, 3, 5]
>>> list(group_2)
[2, 4, 6]
```

When there are 2 groups, the 0th item goes in the 0th group; the 1st item goes in the 1st group; the 2nd item goes in the 0th group; the 3rd item goes in the 1st group... The downside is that the sub-iterables don't have the same order as the parent, but this way we don't need to know the length of the parent.

I'll make a PR for this; apologies for the mistaken dismissal!
