### ISSUE TITLE
Small lie in the documentation of first

### ISSUE THREAD

**Issue by Bakuriu** [erikrose/more-itertools#57]
The documentation for `more_itertools.first` claims:

> It is marginally shorter than `next(iter(...))` but **saves you an entire `try`/`except` when you want to provide a fallback value.**

This is completely false.

The `next` function has _always_ had the second argument to be used exactly as is done by `first`. (See the What's new in Python 2.6 document: https://docs.python.org/3.6/whatsnew/2.6.html#other-language-changes) so calling `first` doesn't save any `try`/`except` if you know how to use `next` properly.

I'd remove that final sentence and, instead, add the fact that `first` is simply a better name for that operation.

**Comment by bbayles** [comment]
This was also reported in #31, and was fixed in 64ee6cc4b38349f68cb7465b3e6045c8bcf0e47b. It will be fixed in the docs for the next release.
