### ISSUE TITLE
`bucket` deprecated?

### ISSUE THREAD

**Issue by pylang** [erikrose/more-itertools#87]
I'm getting a error trying to access `bucket`. 

```python
>>> more_itertools.bucket(iterable, key=lambda s: s[0]) 
...
AttributeError: module 'more_itertools' has no attribute 'bucket'
```

Has `bucket` been deprecated?  If so, the [latest docs](https://more-itertools.readthedocs.io/en/latest/api.html#more_itertools.bucket) need to be updated.

Same for `more_itertools.collapse`.

**Comment by bbayles** [comment]
That one is pending release - see PR #86. Coming soon!

**Comment by pylang** [comment]
I am really looking forward to this one.
