### ISSUE TITLE
Request: Faster `all_equal` for strings

### ISSUE THREAD

**Issue by pylang** [erikrose/more-itertools#88]
**Observation**

I understand the code for `all_equal` derives from the [itertools recipe](https://docs.python.org/3/library/itertools.html#itertools-recipes).   This legacy implementation has the benefit of working with generic iterables.  However, I came across this [SO post](http://stackoverflow.com/a/14321721/4531270), which shows an elegant implementation for the same operation on strings, that is, verify all letters in a string are equal.

```python
import itertools

import more_itertools

s = "aaaa"

%timeit more_itertools.all_equal(s)
1000000 loops, best of 3: 1.1 µs per loop

%timeit s == s[0] * len(s)
1000000 loops, best of 3: 438 ns per loop
```

We see the SO algorithm in this case is 2x-3x faster for strings.

**Request**

Can the SO algorithm be included in `more_itertools.all_equal` so that if a string is passed as the argument, this faster algorithm is preferred? 

For example:

```python
def all_equal(iterable):
    """
    Returns True if all the elements are equal to each other.
    
    Uses a faster implementation for strings. 
    http://stackoverflow.com/a/14321721/4531270
    
        >>> all_equal('aaaa')
        True
        >>> all_equal('aaab')
        False
        >>> all_equal([1,1,1,1])
        True
        >>> all_equal([1,1,1,0])
        False
        
    """
    if isinstance(iterable, str):
        s = iterable
        return s == s[0] * len(s)
    g = itertools.groupby(iterable)
    return next(g, True) and not next(g, False)
```

**Tests**

My local tests confirm these results:

```python
# New algorithm
all_equal("aaaa")
# True
all_equal("aaab")
# False

# Legacy algorithm
all_equal([1,1,1,1])
# True
all_equal([1,1,1,0])
# False
```
**Performance**

There is some improvement in speed over legacy with continued benefits for longer strings.

```
s = "a"*100000

# Legacy implementation
%timeit -n 1000 more_itertools.all_equal(s)
1000 loops, best of 3: 1.09 ms per loop
    
# Proposed implementation
%timeit -n 1000 all_equal(s)
1000 loops, best of 3: 9.64 µs per loop
```

**Comment by bbayles** [comment]
Are your labels backward for the second set of performance numbers? It seems your "Proposed implementation" is much slower in that section.

**Comment by pylang** [comment]
Thank you.  I corrected with values from a separate machine.

**Comment by bbayles** [comment]
Thanks. A few thoughts (some of these are discussed in the SO thread.):
1. This version does not return `True` for an empty string.
2. The downside of this method is making a second (potentially large) string.
3. This optimization probably works for the `unicode` (Python 2) and `bytes` (Python 3) types, and also `bytearray`.

We can probably just catch `IndexError` to fix (1).

I'm most reticent with (2), but I wonder how often it is that you have a truly giant string and you're not sure whether it has only a single character.

I'm not a fan of a bunch of type checks for (3), but maybe just checking whether `len` and slicing work would do what we want?

**Comment by pylang** [comment]
These are good points.  

1)  I prefer duck typing, so catching an `IndexError` works well.
2) I hadn't considered the memory issue.  This version may undermine the point of using a generators.
3) I can't find a pythonic way to duck type all kinds of strings, and coding for each type seems less elegant.

It is amazing how the legacy code inherently addresses all of these issues and maintains it's elegance.  True there is some performance loss, but this is the nature of generators.

Thanks for entertaining my questions.  I would encourage updating the test however to test for different kinds of iterables and the empty string case you mentioned.

```python
class AllEqualTests(TestCase):
    """Tests for ``all_equal()``"""

    def test_true(self):
        """Everything is equal"""
        self.assertTrue(all_equal('aaaaaa'))
        self.assertTrue(all_equal([1, 1, 1, 1]))
        self.assertTrue(all_equal(""))
        
    def test_false(self):
        """Not everything is equal"""
        self.assertFalse(all_equal('aaaaab'))
        self.assertFalse(all_equal([1, 1, 1, 0]))

    ...
```

I am content to close this issue.

**Comment by bbayles** [comment]
Thanks for the comments. If you're content to close the issue, I'll do that now. I added some tests in PR #90; that was a good suggestion.
